### ISSUE TITLE
What's the maximum PyTorch version that the Profiler TensorBoard Plugin Support?

### ISSUE THREAD

**Issue by jgongd** [pytorch/kineto#1009]
I noticed some functions are not working on PyTorch 2.x, and I came across the deprecation note in the [tutorial](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html#use-tensorboard-to-view-results-and-analyze-model-performance). Does anyone know the maximum PyTorch version that supports the tb plugin? I couldn't find the answer from the release note.

**Comment by sraikund16** [comment]
It was marked deprecated on August 23, 2023. The latest release before then is PyTorch 2.0.1
