### ISSUE TITLE
gpu_user_annoation is incorrect on the backward

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/kineto#1022]
The gpu_user_annotation of ProfilerStep# is incorrect when running backward.

When running backward, the CPU side annotation ProfileStep#22 is correct (covers `ScaledDotProductCudnnAttentionBackward0 ` ):
<img width="697" alt="image" src="https://github.com/user-attachments/assets/b2cc83c2-d6eb-4ffc-b60d-40b797f466e7">

However on the GPU side, the annotation ProfileStep#22 only covers the first GPU kernel, and we expect it should include kernel `cudnn_generated_fort_native_sdpa_sm90_knob_26_64x64x128_1x4x1_kernel0_0 `, which is launched by `ScaledDotProductCudnnAttentionBackward0`:

<img width="967" alt="image" src="https://github.com/user-attachments/assets/427b13ac-bbff-4056-b611-1837e6f46b36">

Forward does not have this problem, ProfileStep#XX is correctly annotated:
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/b7cbd829-4e8c-4ab7-837d-35d0683830c0">

Trace file:
[tritonbench-evo-eval_1767401.1733597432912601596.pt.trace.json](https://github.com/user-attachments/files/18049528/tritonbench-evo-eval_1767401.1733597432912601596.pt.trace.json)

How to reproduce using Tritonbench:

Use the command
```
$ python run.py --op flash_attention --batch 1 --n-heads 24 --seq-len 4608 --d-head 128 --only sdpa --metrics kineto_trace  --bwd
```
It will generate the above trace file with incorrect gpu_user_annotation.

**Comment by sraikund16** [comment]
It is doing that because your annotation is only on the main thread but the majority of the backwards ops happen on a different thread. Because of this the user annotation is small because we use NVs thread local correlation stack to determine which user annotations to put in the GPU track. There is no global stack unfortunately, but maybe we can make our own.

**Comment by xuzhao9** [comment]
Thanks for the clarification, I will close this issue for now.
