### ISSUE TITLE
'"ts": 0' event is found in kineto's chrome tracing file

### ISSUE THREAD

**Issue by gaoteng-git** [pytorch/kineto#109]
When I train resnet50 model with big batch size such as 128 or 256, the profiler dumps the following events in chrome tracing file:
```
  {
    "ph": "X", "cat": "Kernel", 
    "name": "volta_sgemm_64x64_nt", "pid": 0, "tid": "stream 7",
    **"ts": 0, "dur": 0,**
    "args": {
      "queued": 0, "device": 0, "context": 1,
      "stream": 7, "correlation": 106123, "external id": 34735,
      "registers per thread": 126,
      "shared memory": 8192,
      "warps per SM": 14.4,
      "grid": [4, 4, 36],
      "block": [64, 1, 1]
    }
  },
  {
    "ph": "f", "id": 106123, "pid": 0, "tid": "stream 7", "ts": 0,
    "cat": "async", "name": "launch", "bp": "e"
  },
  {
    "ph": "X", "cat": "Runtime", 
    "name": "cudaLaunchKernel", "pid": 29463, "tid": "3239786240",
    "ts": 1615207264505000, "dur": 6,
    "args": {
      "cbid": 211, "correlation": 106123,
      "external id": 34735, "external ts": 1615207264504915
    }
  },
  {
    "ph": "s", "id": 106123, "pid": 29463, "tid": 3239786240, "ts": 1615207264505000,
    "cat": "async", "name": "launch"
  },
```

You can see "ts" is 0 and "dur" is 0 in above kernel. And there are more than 1 thousand these events in the file.

The model code I used is [plugin example resnet50](https://github.com/pytorch/kineto/blob/master/tb_plugin/examples/resnet50_profiler_api.py), and changing its "**batch_size**" from 32 **to 128**.
The GPU: NVIDIA V100.
The torch whl: https://download.pytorch.org/whl/nightly/cu111/torch-1.9.0.dev20210305%2Bcu111-cp38-cp38-linux_x86_64.whl
The torchvision whl: https://download.pytorch.org/whl/nightly/cu111/torchvision-0.9.0.dev20210305%2Bcu111-cp38-cp38-linux_x86_64.whl

Because these kernels with 0 ts are launched by the runtimes which are nearly the end of profiling, I guess it is due to these kernels are executed later than "profiler stop". This is my snapshot:
![image](https://user-images.githubusercontent.com/10429114/110324548-194b3e80-8051-11eb-9ba2-2b67a589b24c.png)
You can see the kernels that which should be executed after "profiler stop" is not painted here(They are painted at time "0"). And the last operators don't have related kernels, but they really launched kernels in chrome tracing file.

The is also bad experience that user will be confused to see the following in this case: (ts=0 will make these events starts at 0, and other events will be shown to many years later)
![image](https://user-images.githubusercontent.com/10429114/110325019-c45bf800-8051-11eb-951e-e7468926fb70.png)

BTW, the expected behavior is correctly dumping the kernels launched during profiler's start and stop, rather than removing these kernels from file. Because we have to make the operators' kernel time to be correct.

**Comment by gdankel** [comment]
Usually GPU events corresponding CPU events but with timestamps before the CPU events will be filtered out. This won't fix it the way we want since the GPU events will still be missing, but it will at least avoid this situation with GPU events years in the past.

**Comment by gdankel** [comment]
@gaoteng-git Do you still see this in 1.8.1?

**Comment by gaoteng-git** [comment]
> @gaoteng-git Do you still see this in 1.8.1?

No. Thx!
