### ISSUE TITLE
Intended usage

### ISSUE THREAD

**Issue by tgerdesnv** [pytorch/kineto#12]
What is the intended usage of this library? It doesn't look like there are any examples or blog up yet.  Do I need to build a C++ program around this library? How do I then invoke it while running a python pytorch run?

**Comment by gdankel** [comment]
@tgerdesnv We will provide more details soon. The repo was made public to allow integration into PyTorch and enabling CI. But it's not quite ready for primetime. Why are you asking?

**Comment by tgerdesnv** [comment]
@gdankel Thanks Gisle. I was just curious what the output will be and if it is something that could be consumed by another tool. Will there be an output that includes operation details (shape, inputs) combined with CPU + GPU timing information?

**Comment by gdankel** [comment]
Yes exactly, that's the starting point.

**Comment by aaronenyeshi** [comment]
PyTorch Profiler API is using Kineto for GPU trace collection. You can modify the checkout of Kineto in PyTorch directly via pytorch/third_party/kineto. Closing this old issue.
