### ISSUE TITLE
Profiler gets stuck on trace handling for a toy training loop

### ISSUE THREAD

**Issue by Antymon** [pytorch/kineto#126]
**Basic setup info**
```
device: Tesla V100-SXM2-32GB
ram: 64GB
pytorch: 1.8
cudatoolkit: 10.2
python: 3.7.8
environment: conda 4.7.5
os: CentOS Linux release 7.9.200
```

**Description**
Hi, I tried to export profiler trace for 1 epoch of training for a tutorial toy problem with examples of your new profiler API. Unfortunately, whenever training finishes and trace handling is called either via profiler or manually it gets stuck indefinitely, never outputting anything. I observed that from the moment of entering the trace handler RAM consumption of the host increases from 10 to 25GB over couple of minutes and stays there. Mindful of legacy profiler issues I checked the impact of setting `DataLoader`'s `num_workers` to `0`, but didn't seem to play a role. Any help appreciated

**Conda's `environment.yml`**
```
name: torch18
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - matplotlib
  - cudatoolkit=10.2
  - pytorch=1.8.0
  - torchvision=0.9.0
  - request
  - request-oauthlib
  - pip:
    - tensorboard==1.15.0
    - tensorboard-plugin-wit==1.8.0
    - torch-tb-profiler
    - pynvml
```
**Minimal Example**
```
import sys

import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms

device = torch.device("cuda:0")

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True,
                                        transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4, shuffle=True,
                                          num_workers=2)


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
net.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

tb_handler = torch.profiler.tensorboard_trace_handler('./log')

with torch.profiler.profile(
        activities=[
            torch.profiler.ProfilerActivity.CPU,
            torch.profiler.ProfilerActivity.CUDA]) as p:
    for epoch in range(1):  # loop over the dataset multiple times
        running_loss = 0.0
        for i, data in enumerate(trainloader, 0):
            # get the inputs; data is a list of [inputs, labels]
            inputs, labels = data[0].to(device), data[1].to(device)

            # zero the parameter gradients
            optimizer.zero_grad()

            # forward + backward + optimize
            outputs = net(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            # print statistics
            running_loss += loss.item()
            if i % 2000 == 1999:  # print every 2000 mini-batches
                print('[%d, %5d] loss: %.3f' %
                      (epoch + 1, i + 1, running_loss / 2000))
                running_loss = 0.0
        p.step()
    print("epochs done")
    tb_handler(p)
    print("export done") # never gets here

print('Finished Training')
```

**Comment by ilia-cher** [comment]
will comment more today, but from the code provided - the API is not used in the right way, you shouldn't call tensorboard_trace_handler directly, and, at the very least, it shouldn't be called from within an active context manager

**Comment by ilia-cher** [comment]
Hi, thanks for using the new profiler, we added an experimental support for it in 1.8 and plan to stabilize and make it default in 1.9.
We'll make sure to add more to the existing tutorials on the new API. In the meanwhile,
- in your case `tb_handler(p)` should be called after profiler context manager is finished
- since you're not using `schedule` parameter, there's no need to do `p.step()`, profiler is going to profile everything in your example
- when trace is too long, it currently takes too long to process the events  - it's a KP and an action item for 1.9 release

**Comment by Antymon** [comment]
Thank you for your reply @ilia-cher !

So I understand it is okay to call `tb_handler_manually`. I extrapolated this use pattern from how `p.key_averages()` was used in[ docs examples](https://pytorch.org/docs/master/profiler.html#api-reference). As for why I believed it is okay to call it from within context - I must have confused the formatting.

As for the core of my problem, at the high level of my example it seems it is related to the use `torch.profiler.ProfilerActivity.CPU` (of course I am sure that the root cause is just as you described). If I just leave `CUDA` activity I get the profiling output reasonably quick. If I leave CPU, the longest I waited was 30 minutes and I gave up.

Thank you for your awesome work. Can't wait to see how this tool evolves.

**Comment by gdankel** [comment]
@Antymon I'm spending some time looking into issues such as yours. Is this still relevant?

**Comment by Antymon** [comment]
@gdankel Thank you for your concern. I did manage to do what I wanted at a time after some of the explanations and discovering examples (I believe that at 1.8.0 docs were a fraction of what they are at the latest now). I may have not used CPU mode at all though as it was not my main interest. I leave it to your judgment whether you want to do performance testing for this. It ended up not being a blocker for me, but I haven't worked with Kineto ever since, haven't used CPU mode and I see some ppl thumbed-up my previous concerns which may suggest there is some interest in the problem after all.

**Comment by guotuofeng** [comment]
link with another [hang](https://github.com/pytorch/pytorch/issues/60158).
