### ISSUE TITLE
Profiler plugin does not refresh traces

### ISSUE THREAD

**Issue by lenisha** [pytorch/kineto#130]
Running training multiple times generates more traces, but refresh button does not re-scan the log directory and does not show new traces

![image](https://user-images.githubusercontent.com/6332907/112351299-25b1d700-8ca0-11eb-89fd-96def7d80bef.png)

**Comment by Kingwl** [comment]
https://github.com/tensorflow/tensorboard/issues/4829

**Comment by Kingwl** [comment]
Latest tensorboard has support refresh now. https://github.com/tensorflow/tensorboard/issues/4829#issuecomment-819917959

**Comment by gdankel** [comment]
@Kingwl can we close this?
