### ISSUE TITLE
Profiler plugin arrow navigation in VSCode

### ISSUE THREAD

**Issue by lenisha** [pytorch/kineto#142]
When TensorBoard with Profiler plugin is opened in VSCode key navigation with arrows does not work, while it is working in regular browser

**Comment by gaoteng-git** [comment]
> When TensorBoard with Profiler plugin is opened in VSCode key navigation with arrows does not work, while it is working in regular browser

The keyboard arrow works when navigation on right content side. But it can't work on left panel checkbox when navigation up and down when launched in VSCode.
![image](https://user-images.githubusercontent.com/10429114/114501834-51036280-9c5d-11eb-98e0-3f6a5223226c.png)

**Comment by gaoteng-git** [comment]
Works when re-tried.
