### ISSUE TITLE
[Task]: Trace torch.nn.DistributedDataParallel and torch.nn.DataParallel forward

### ISSUE THREAD

**Issue by guotuofeng** [pytorch/kineto#148]

**Comment by guotuofeng** [comment]
https://github.com/pytorch/pytorch/pull/55578

**Comment by qshzh** [comment]
Thanks for this amazing tool.

I am interested in profiling my training with orch.nn.DistributedDataParallel. Does the profiler support ddp? It seems there are no [related tests](https://github.com/pytorch/pytorch/blob/84a7ab250bd1db6ff72d8b0e01f046e9955da65f/test/test_profiler.py#L152).

**Comment by nbcsm** [comment]
Currently, you may turn on profiling for each worker in DDP, and export all profiling results to the same folder.
Then you can select each worker here:
![image](https://user-images.githubusercontent.com/32868157/114295837-4a001700-9ada-11eb-8a82-f1b1a732ce42.png)

But right now, there is no _special support_ for DDP yet.
We will add Distributed Training View for DDP in next release, which is designed for distributed training scenario.
Please stay tuned. : )

**Comment by guotuofeng** [comment]
https://github.com/pytorch/pytorch/pull/55578
