### ISSUE TITLE
[Document] Profiler API Documentation

### ISSUE THREAD

**Issue by guotuofeng** [pytorch/kineto#174]
Update API Documentation https://pytorch.org/docs/stable/profiler.html

Feedback from Users:

- Document difference between “wait” and “warmup” parameters in profiler schedule. Will be great if their meaning can be clarified in the documentation.

- Explicitly state in the PyTorch docs that additional plugin needs to be installed to leverage tensorboard. You have the link to github, where it’s clearly stated, but it should be more explicit in my opinion, so I suggest to put that clarification in the main PyTorch documentation

- Document profiler.step function. Maybe documentation can be improved. 

- Document record_function. Is there any way to mark regions of the code to be grouped together in profiling?

- Document trace events lifecycle. Our current code has infinite loop in a function, out of which we return from the middle when some “exit condition” is satisfied (either number of steps or if validation loss stops improving). While we can definitely refactor that loop to “normally” exit and thus trigger the “__exit__” call to the profiler context manager, it will be good if there is some helper functionality (or at least an example in the documentation) on how to best handle such structure of the training loop. I think that tb events are still properly logged, but if I try to summarize the p.key_averages() inside the “with torch.profiler” block (before “return” operator), I get a “RuntimeError: can't export a trace that didn't finish running”. Again, this is not a big deal, since we can refactor the code, but will be nice if such structure is generally supported (maybe it already is, then will be good to have examples in the docs).

**Comment by gdankel** [comment]
I think most (all?) of these have been addressed? Can we close? cc @guotuofeng

**Comment by guotuofeng** [comment]
yes, I forget to close it.
