### ISSUE TITLE
Loader doesn't correctly parse trace filename when repeat>1

### ISSUE THREAD

**Issue by chokkyvista** [pytorch/kineto#179]
https://github.com/pytorch/pytorch/blob/7d4e9bdba144e162882fb854324430c4b92fb267/torch/profiler/profiler.py#L75
Here's how `tensorboard_trace_handler` decides the filename
```python
file_name = "{}.{}.pt.trace.json".format(worker_name, int(time.time() * 1000))
```
And here's how the loader parses it
https://github.com/pytorch/kineto/blob/b4e71c3a9e11814bcbb2fb44bfb8bd7d2908b77f/tb_plugin/torch_tb_profiler/profiler/loader.py#L43

When `repeat > 1`, there will be multiple trace files from each worker under different timestamps, and yet they will be identified as different workers by the loader.

**Comment by guotuofeng** [comment]
From the time being, only one trace file is supported and the multiple file support would be in next release.

**Comment by nbcsm** [comment]
https://github.com/pytorch/kineto/issues/156
