### ISSUE TITLE
PYTORCH_PROFILER tab is not getting rendered automatically is JupyterHub's Tensorboard

### ISSUE THREAD

**Issue by chiragbajaj25** [pytorch/kineto#181]
The .json files are being saved by profiler at the logdir, but when I try to open tensorboard from jupterhub, the pytorch_profiler tab doesn't seem to be rendered automatically. All the dependencies as mentioned in README are present in the hub environment.

**Comment by guotuofeng** [comment]
Hi, @chiragbajaj25 , what's error you hit? I try in windows to load our plugin in jupyterlab, it can load succesfully.

**Comment by guotuofeng** [comment]
Is it like issue https://github.com/pytorch/kineto/issues/194?
