### ISSUE TITLE
Separate traces for training and validation steps

### ISSUE THREAD

**Issue by lenisha** [pytorch/kineto#188]
Our code is structured in such a way that inside the main training loop, we will sometimes run validation as well. Ideally, it should be logged separately from training. Is there any functionality to support this? 
E.g. similar to what this issue is asking for: https://github.com/pytorch/kineto/issues/86, 

but ideally we should be able to span a second instance of profiler (or provide some metadata to say that current steps are not for training, but for validation).

**Comment by gdankel** [comment]
OK let's discuss how we can do this - so a common use case is to capture X iterations of training and X (or Y) iterations of validation, usually once, possibly periodically every Z iterations?

**Comment by gdankel** [comment]
Is this addressed with 1.9 API or do we need additional support?
