### ISSUE TITLE
Plugin fails to load traces

### ISSUE THREAD

**Issue by lenisha** [pytorch/kineto#194]
Running BERT training:
``` python /home/azureuser/pyprofiler/bert_for_sequence_classification.py --train-steps 64 --epochs 2 --pytorch-only```

https://github.com/lenisha/pyprofiler/blob/main/bert_for_sequence_classification.py

and producing following trace:
https://github.com/lenisha/pyprofiler/blob/main/trace/bert_record_nt/worker0.pt.trace.json

Plugin does not load the trace , just showing spinner

**Comment by guotuofeng** [comment]
should related to https://github.com/pytorch/kineto/issues/189
