### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'overview'

### ISSUE THREAD

**Issue by guotuofeng** [pytorch/kineto#232]
AttributeError: 'NoneType' object has no attribute 'overview' is raised when switching logdir at tensorboard startup

Repro step:
1. start tensorboard using command line:  tensorboard --logdir=./bug_repro/version_1 --bind_all
2. open the url reported in command line.
3. ctrl+c to terminate the tensorboard process and keep the browser open
4. start another tensorboard process: tensorboard --logdir=./bug_repro/version_2 --bind_all

Expected: 
the process can be launched successfully

Actual:
![image](https://user-images.githubusercontent.com/817030/118613119-055e4e80-b7f1-11eb-8d41-886c27bae060.png)

[bug_repro.zip](https://github.com/pytorch/kineto/files/6499341/bug_repro.zip)

**Comment by guyang3532** [comment]
fix at https://github.com/pytorch/kineto/pull/233
