### ISSUE TITLE
No Empty State for TB Plugin

### ISSUE THREAD

**Issue by Reubend** [pytorch/kineto#270]
If you load the TB plugin on a log directory that _**does not**_ have any traces inside, it will display a loading spinner endlessly. I think there should be a message saying that no traces were loaded; other plugins (like the graph plugin, hparams plugin, images plugin, etc.) behave by displaying such a message. 

Expected behavior:
the TB plugin should say that no traces were found
Actual behavior:
A spinner shows up but no error message ever shows

<img width="1424" alt="Screen Shot 2021-06-02 at 9 00 14 PM" src="https://user-images.githubusercontent.com/13208038/120570193-8c144d80-c3e5-11eb-8dc3-aaf66db1fa38.png">

**Comment by xilin1991** [comment]
I also encountered the same problem。

**Comment by xilin1991** [comment]
I solved this problem in my environment. You can uninstall 'torch-tb-profiler' in your virtual environment(such as anaconda).

**Comment by Reubend** [comment]
> I solved this problem in my environment. You can uninstall 'torch-tb-profiler' in your virtual environment(such as anaconda).

Maybe I don't understand fully, but I don't want to uninstall it. I just want it to show an empty state message when there are no traces found.

**Comment by xilin1991** [comment]
Do you want to see the results of the model in Tensorboard dashboard?
Tensorboard can work even after uninstalling 'torch-tb-profiler' in my environment.
During this process, there will be a warning in the following picture.
![warning](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAdMAAAByCAYAAAAIyTtSAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABbfSURBVHhe7Z1tqxzHlcf3S6wXsg44MY4x2Bg2RLCsjAKCzYsVKEIxi2KiRBGKTUxgY6JoQXsvWoJs5UEE+14IgmAMF3wVUMwKCQljCDL2JdKrvBB6ZfuNvoHzBWr71EPXOadOdc9Mz53pmfsX/HB3V9WpU6eqzr+7Zzz3H/7pq087AAAA4+I7/3Hc/d/Nm/6/VrnFLG3AfICYAgDACPnKU8+437+95T799FO3t7c3EVSX2lBbyybYPyCmAAAAwEAgpgAAAMBAIKYAAADAQHrE9OuZJwEAAIADANc+UxtLKmIaDTY8AQAAABxApLhaWplRYhoaWUYBAACAg0rSR6mZGSamTSXDwBNPfg0AAAA4gEg97HpKFWIqG0Zj/1zyjwAAAMAaYWmdJao9YspFlIgGGmO5s6cAAACAAwAT2CcTWSMtQQ1iyiqVQhqNfwUAAAA4ADBRtQQ1vO4txDQUCDFNQvr0CwAAAMDBRQgqF1MpqF5MTSElVbYMAwAAAAeF4gk1CirEFAAAAJiQicW0FVIupk1jem9sGQYAAAAOCvEz1EJMCYgpAAAAMAEQUwAAAGAgs4pp+3kpxBQAAMBBJ4qp/9wUYgoAAADMAMQUAAAAGAjEFAAAABgIxBQAAAAYCMQUAAAAGAjEFAAAABjIssX0xWcPuf8+/LK79p1X3HtHm/8ePur+81m7LgAAADBKliamzx11773yv+7x5lX3+PyGu/+Dn7uPf3DBPTr/G3/t0Ssvu9e/YbQDAACwZhxyR1+75C5euuw5/9r33FNmvRGzDDF98Zs/dH+7cNV9fu6cu/y8Uf78MXfj3Fvu8YWL7v1vluUAAADWiTfcH/5yz93+03W386c77t5f3nXnzHojZuFi+txJ93EjpI++e9S9aJUz3vhu8+R64RfunefscrAIXnUbHz5wG6eNstM77vpepWze+L5uubP+/Irbavul44dua5PV3SfO7j5017dfNctWnWWO7cj2A3e3mcO7H+6403Tc/PcIlYk5B/OD9swY4nrc/df2u+7imX93/3Li9+6Dezvup/76L9279266N080189cdn/Y/h93uGg7Lc2T77HjxvXA4WNzeBJetJhe/n7zxHnmZXfCKCs55K6d+Y37/PvHqsJrJQG/OdOGTGzeKq+BCegQ08GQ7QmFsCqm+0Xp23wEJ9j14pHYvWLUY9Da5fVb5pcQJx/bDP530jGXcxHTcLMl/I0s4gasThnHxd3MjENMT759x+19dMd98NGe2/vkjnv3fBa7w+d33O1Pmusf3XS3m/Lbb/9YtJ2aU9uNvTvunZ/8W1H2zE+u+bKrp+T1qVmomD57yt3f3HDvv5Cu/au7dnrDffztQ22dEy+97h6dPeVOpzYv/ND9beOCu1b7UpIhkpQY7qoNSgK7rDvv1YY2PcSUmJ+Yct9DP5PanY8PJdOJ6ez+l3Qk9nk/mY7qhlrHcRFrOjECMT1y2V3/pHn6PMmufevH7qdv/dpduvRLd/Jb7PrJ5qn1kxvu4hF2bQaSaHJBta7NzCLF9MWjv3CPf3bGvc6unfj2z93nF9/ygsqPc7uX3I2fXXX3j+Y2Er0wwvlWkxxyIgwbvj33mzTdEdYWVVzc2+GpICWL9pUUoe7IRRnbtEHcE9rX3AfhfWRPImUy32naRFu+f7LBz2X9ZIcnu2Dnio9JKJcx4OMI9SqbnCe7dMx8Fwm2iDnzm0jxEvX0nCU/Y9y8T/x4XmOzfStty7ZdayOjk2gDxYzqV24My7njwqV8Zf16f3Z3or85DtY67RtbpsP/5jjYiWu0Mqet/8b14HMcg5hzXV9fv9XsozAuvmcElfjy/sP1uKY2WX9iPnnMeSymmQsdR5WjUhuznwYVO71PdCz4OLc2yU+5LxbO8V83AnnPffC718Lr1SOX3M499pnpvevuvBfPQ+7U7266e43wXjrO2s8IF8+5CimxSDH1n4H+6GRxPYjoVfe4ENLAOz+iz1iPFNcDahHyxGRuyrhR0sI0Nlggbgy+iVRdntj8wudlTUKhY31d2lB9UFlxnhd92BB8HOV5ioNISipGwU6OgT/nfTJ/w4ZWGznB45o2d7Ljz1M7FfMWK4E0iYDPjbDPx2rbntvYDN+msU1lUvQSZFf1SW29HR0nOk9jDki7wUfeDy+3xqfXY1qnnWMTdPmf7HCfaQw8jjqucoxi3U66b+Pas+PNsOa/HSP3K/ic6/IxaP8T086FiiONgfnmfeVxFLEge137RPohx2nN0XJ46ljzdEqfjTYieZQE849vxM8tD7lzfySh/V4juvRZavNUeqzUhVkJIhpeLc9NSInVF1O5WGih+IXOFx/b7Hph6c0sr+vFrzZRa1dtjBZtg+B1dXn3Od+c3edlvzTuVFe3y0nGGGN1bA08xmqzy3hZdruuJ2gcln0+vu4YzTw2o/5Uttmak+g+yf/clvpo7Rg2hA9t/7ncxyleK9d6fbz1scl6k/jP7ZQ+NIhxsTluEPXZnHfu22LtVRBjkuuGyHukLOPjKmJFzDQXJGqZvH6M9dRA/eprga5YlGMR9ZcIxNQzm5juz2vehnbR8o2ej/ni94uaLeCAXmyEXoTl4vf4fmuL076eN4Xuo/tcb+L6ObUzfI2bWbez45ewrkX4xi02MR8nkX3qThrad8s+j0t3jGYem+Fbt23uc8SX5faBsq4YPxMaGb+A8EGIUoLiEeLUKUCK+thkvT7/tZ0sULmOtC19Ej6zOe/ct6ye6EdTiKm21+D7lmuKkOPIMZh9LsiG7CPHriwjpA/a/zj+IhYyvvVrCwaveYeJqfUFpPfObriPXsriSYL66PTL8gtImxfce52/ihQXH33GwRJAWHzyczG5ILvQG8pe4Hbdruvcji7vPteJqn5O7eqbRbfLyY18s8RNjyHCN66R0KgfLQbSnu7PGr9ln9eTbeY2NqN+t+2aHU1fXSqncbKxM4QPUz8N1cdbH5us1+e/tlP60CCER45T1Gdz3rlvWT2zPFGIaa1NGSe7f7ZGpp4LI45tXJjdtn6Ibbim/WNjKWJRjmXieO0n+ALSQDFtmPf/GpOghSbuFAm/aJrrfJH7a/VkkLE3VLFhIr5/ViY+i+Jtig2tN0X9XCeqrnPfr05iEd2u2PTMX39eixfflMYGpX50QpCJQiUNbYNiZdrncemO0cxjMxLaNLbrGElUQba2dm/JviLSBxq79ImXe5/UGqBy7idfp7Wxtdc83f6bdhofcxx1XGkMec6Fz3zO/XGlX16vCyV4PhbmHpFriiC/xLgiebzTzkUZx6I+H1MRC1ZW3ScBPU5/ruosA/yvMZ7ZxXTffrTBLyi92coFnuvSgopMuKGIsBAzOtlaNsV1kaB0H93nZKe2WcvzkLTafjvs+A2ok0xsV//Ga0PXBm8gOyE+YR6yTdZ3movYf0gisW4jKPYdN49Ld4xmHhuhfJvGNsHXRqZfTMNY7TqFDx2xLRN4QPgZy/vGlplSTAk/ntynjAv5n9eN8Nm3Y2uqtm91vRrUXoyptkfkmiLIrzAu1UbEd5q50H03iHK1F9T4RFl1nyRkX6P4Nq8HP9rgK84spg34OUEwDsaSVBRVIQNgXcHPCc4kph780D1YMv4JTT0NjAHyy36qBWBdwQ/dzy6mEfwJNrAo5GuzhrE9/aXXmCMUeABAD8sWUwAAAGDlgZgCAAAAA4GYAgAAAAOBmAIAAAADgZgCAAAAA4GYAgAAAAOBmAIAAAADgZgCAAAAA4GYAgAAAANZezGd9Eew+/B2en6gfESYPzje0v1j5fuN+NFvHtd5zdUAFvkTg3yOyh9CrzNN3UUyVr8AWAgQ00UR/nKD/s1VK3nPIymtjJhy5jFXy57v4i+T1JlUTPVcQkwJ+ZdQ6msdgAUBMV0cZbJJCUH6R8lz6A+dQ0yNskUAMTXL5k4zzxvtHin/ZBoAC2f1xTRupE1KovFOlScznlzpWCS6UlQocaW7XfF3/0SSNvqcJIno/v35LbclfJCJgfsjRZf5FqG6SYTNBBzt1P+OZxB3IeTFuJk/bMxkX4h3EeuMSLrcvugr3mgwGzwW5o2C+nuXuU7dbw2PWzimWKW2Zbx5XzzGRIij7Jv7zfuyhSjdbCVC/6ku77+cM9lG2g2U46vvheIGQcRa+uXLow9ifKp+ssXLrLWp45yuZ8q9AMDCWQ8xbTaaTrq1ZC2SghRTndDCJmZt2w2r+wzn/U+TVE/2l5JwmyTYk433h/srnnrKBEL+mmKqnpZC8rLEtIxB9i0kdp7MeB9iDEQR64zoQ89PPBZzqNtYop8Q80R0+63hZd4HfWMTfdBxalGxpvPWT++btMfjZ9pr0P76umy9+XOxLtjcan8Yeny+Ll/jKt6tD6Ie9b/jj/MY9H5o2u9mH3gctX9hbNknGRdr3ukaGwMAy2Jtnkz5ZqokaH8sEgvfiIYdf82wY9TVCa9Grsf6ZgmFkkcot/zR/uaElmynRCP7mSIBiRjZPlp1s99lWXstIhIkj2s83qBy0baMRdFfgtsjevxur0X4PBZzym1Zdruue2TcuX0pGhLtR1GXjbm0U66TRDE+c60EeLypXa3O3UY09c1LAcXI+9i3NvvmXcYTgKWylmLKE4hO1iLR6Y2rk07FTu8m76BNJLy/dMyTi+UPT2RlOU9yOVFaCacrCbEyHq/Wb143+1CMv4h1JiTdaEvPDz3xm/NJ1xWFPw1inhp6/JbXpcDwY48akx8H+cHHWYhpmNPsdx4bty9iotB+lHXlPOS+yj45xfjitbSGtK1Qt752zHgkKC7MVvC/b232zXt9HgFYOGv7ZJo2tE7WRaLjG9eww9u2G7esS4lEJyabmABUkg9JjCcHw5/C31Q3wBNhTpTUJl8PWLYZjW/UVoypEIkGFs9i/EWsMz7pprFbMfaJl4+tHGsVMU8NPX631yJcYPixp9JOjEf0p2PP50/aFzYU2o+ybo5PMQ8dFONj/uk+sl1rPeU61IbsCv/0HNC5L+9bm1PMOwDLZj3ElG/esEHbJCGSK9+ocfOzc50E/Hlq22En2epLNoFQTnfYoo4XEKN/nYRqiTq2T+c8UfpxMjt63CXN+PwXo3giC3HmyZf3YfkmfGekpOvPeVzZcfAx96/npoqYJ6LHbwUvK+qRbWtMfOwiDmqdeN/kekv2RUwU2o+yLvXDY9g1txmyKz/7bOxG32Wfck/puSk/M43zH33U/vp+eRmLabAtYyTHylF7AIBlsjZPpttBTLQg6eQaNmuoV35zMCaBWN77bV6WsMhuSDb9Gzz4kH3yePtlu5DwIjqRRwH1NGOmupaYajv1b/Nm7CRG4+Z2sn0Zu8Y2fdNZ+xvx40+2eVzVXAWfk59ybrpuBtJYs39dfkt43Pixh/yLY+LrSM5l9tPPBZ8j9c1tbl/ERBPXRuqnrMvWKcH7JCp2Q/87LDZ8HDxmD9zWrnziFePnMWn7iu19mdpXu41/zKc0X0TfnpTzHsogpmAUrI2YVhLrIFjyNMvXGEpwSFLrTXGzMArUjQEAqwLEtEa46x1fslkAB/gm4iAxRjH1T6m1J3QAxgzENMNfN3kO3KZOr9T26UkfjIoxiKl8Xd6Amziwqqy+mAIAAABLBmIKAAAADARiCgAAAAwEYgoAAAAMBGIKAAAADARiCgAAAAwEYgoAAAAMBGIKAAAADARiCgAAAAwEYgoAAAAMBGIKAAAADARiCgAAq81Xn3l+tFj+Wlhtx4DlqwnEFAAAVhtLBMaC5a+F1XYMWL6aQEwBAGC1sURgLFj+Wlhtx4DlqwnEFAAAVhtLBMaC5a+F1XYMWL6aQEwBAGC1sURgLFj+Wlhtx4DlqwnEFAAAVhtLBMaC5a+F1XYMWL6aQEwBAGC1sURgLFj+Wlhtx4DlqwnEFAAAVhtLBMaC5a+F1XYMWL6aQEwBAGC1sURgLFj+Wlhtx4DlqwnEFAAAVhtLBMaC5a+F1XYMWL6aQEwBAGC1sURgLFj+Wlhtx4Dlq8nCxXTzlru79zByy5216iydV93Gh8lH4oHbOG3V6+D0jrv+4Y47YpXNC4pl7OPI9gPmb8PuFbvNvnLFbc0Sq5YQ961NqwwAUMMSgRq7Xzj35V9/W1z77IasNy8sfy2stnV+6/a+dM598Wd1/c/usy/vu1+Ja8OwfDVZqJiSwHABbc43Rpk4KakzUdB+W2jx3HcxlT6SmF7fflXVqaHGNyb2PW4ArB+WCFR58777UgjO/AWIY/lrYbWtQ2L692Yc+ibgoIgpPUkt5YlpWrTYTCA+ixZTss9iuTZiOmrfABgnlgh0wZ9Ef/XXRpTUk+o8sfy1sNrWCWK6d2P/bwwsX00WKqb+NeDDatI/u8teUzIhouv81R8/98fbjbC0dikZZzttOxKfZLt9yqwlbn09nZevMan/6+/fZrZjn1FMz7avX8t2qT4faxDFK3kMFUHW4mmKqR9zfqL2vm5fFfFpb2746/e2Txpv056V5Xmw4hzrx/5kzHnbLrvT3hgAACwR6OQGvesl0WnEx33hduN1Etn0LwtsfKUa/037Otjy18JqWyeK6Zv6tbUSU3oKj37Tv1leZVu+mixWTImchHkC9eKinrTSuRdMVTed+3ZKeE1R4aLUPiFPKKZUP7aXiZ6Jh+4jCkmqq8dTG6s/boU3xIqPPaFjEtqFuBK8X3/cjpnqG+NT/oT2ND7mK4uDbhNQ8RA3EFSWzjvspvPCNgCghiUC3QQx+uyL/FQqPzfNYuWFt/hscnIsfy2stnWYf/6GgB0nMfVCmq7repNj+WqyeDFNhIQaBIGSO3uiacvDNS0c/FyWsWTOoeQcRaaFJ++CIGK5PrPJRZMnfUtMzfPusWYhC2X6PGGJqVUvj4X3KcWU2orYEH5cOp7s3IulvnFh5U1stD9SpCt2CYgpAFNhiUAvJJLtU6l8+kz/vLjGp7tZXwVb/lpYbetwMW1oBZ+JaXNN+zzLK23LV5PliWlDmzTnJKZawBJTJ2cpNpqzu6Es/ddfH62Yhrp9Ymq37RG9BmpL4ht8YeUQUwAWhiUCvYgvIilxMiAhagXWKK9h+Wthta2j/Q03A5/dOChi2iRJLQApafqEzxIoL+PHIfFWxNSLROU1r/rMMlATzW4xDUKx47YmEs/yvG+s3H99XrveW08IlBoflSmRDPSIXqK1zcqLmFNZOu+2WxsLAMDGEoFe1Ld6/eelfa9zZ3jla/lrYbWtY4i/Hw99w/dAvOYNYte+SuRi01lGyTaVNYLMBFQ/ocm6rMwLRr4ekvWMYhr7kP1m//31TnGtj3VSkZTiGOq19pJNIZKhz2Srrc9EnLcPY+sQPRHPVEfVVzHP8eqw2xt7AIDGEoFelJimp7v8L74C9q+D07/8ZaVJsfy1sNrWsZ+k/Q0BH5Pwfe2+gLQOaDFYBmsqOvomBADQiyUCY8Hy18JqOwYsX00gptPjn+LYU+HSoCe/tRKe8PQsn/gBAH1YIjAWLH8trLZjwPLVBGI6DfRE+nDNBAwAsOpYIjAWLH8trLZjwPLVBGIKAACrjSUCY8Hy18JqOwYsX00gpgAAsNpYIjAWLH8trLZjwPLVBGIKAACrjSUCY8Hy18JqOwYsX00gpgAAsNpYIjAWLH8trLZjwPLVBGIKAACrjSUCY8Hy18JqOwYsX00gpgAAsNpYIjAWLH8trLZjwPLVBGIKAACrjSUCY8Hy18JqOwYsX00gpgAAAMBAIKYAAADAQCCmAAAAwEAgpgAAAMBAIKYAAADAQCCmAAAAwEAgpgAAAMBAIKYAAADAQGYV0ycgpgAAAEAgiilpI8QUAAAAmIWJxPRp9/9cT4oUpkZKcAAAAABJRU5ErkJggg==)
Choose option 'no'.

**Comment by xilin1991** [comment]
Do you want to see the results of the model in Tensorboard dashboard?
Tensorboard can work even after uninstalling 'torch-tb-profiler' in my environment.
During this process, there will be a warning in the following picture.
![1](https://user-images.githubusercontent.com/31728595/122778853-ee26eb00-d2df-11eb-8aec-c3ec27f83137.png)
Choose option 'no'.

**Comment by guotuofeng** [comment]
@Reubend, this is a known issue and we will prioritize it and fix it in future

**Comment by guotuofeng** [comment]
https://github.com/pytorch/kineto/issues/130 need to be considered when do the fix
