### ISSUE TITLE
PyTorch Profiler Kineto is not available - windows OS

### ISSUE THREAD

**Issue by kjnm** [pytorch/kineto#280]
Hello!
I want to use PyTorch profiler as in this example:

https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/

But I get error:

AssertionError: Requested Kineto profiling but Kineto is not available, make sure PyTorch is built with USE_KINETO=1

I instaled PyTorch by command:
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

My settings are:
python: 3.9.5
OS: Windows 10
cuda: 11.0
GPU: RTX 3060Ti

Probably it is because windows OS.
Have you got plans to support windows OS?

**Comment by ilia-cher** [comment]
Hi, thanks for the report - we're planning to release PyTorch 1.9 this week with expanded platform support for the new profiler, including support for Windows - please try 1.9 or, alternatively, you could build PT from the source or use the nightly packages.

**Comment by guotuofeng** [comment]
@kjnm, would you please help check whether Kineto in windows supported or not in release 1.9?

**Comment by cowwoc** [comment]
@ilia-cher Any update?

**Comment by guotuofeng** [comment]
we are working on this. https://github.com/pytorch/pytorch/pull/62175 is pending to merge.

**Comment by guotuofeng** [comment]
https://github.com/pytorch/kineto/issues/356

**Comment by cowwoc** [comment]
@guotuofeng Is there any way to use `PyTorchProfiler` on Windows until this is released? When I try using it under PyTorch 1.9.0 I get `UserWarning: CUPTI tracing is not available, falling back to legacy CUDA profiling`. Thanks in advance.

**Comment by guotuofeng** [comment]
@cowwoc, I think the Windows support should be ready when PT 1.10.

**Comment by cloudhan** [comment]
This feature will NOT be available in 1.10

**Comment by EtienneDSamson** [comment]
So if I understand correctly, it is not possible to fully use the Pytorch Profiler on Windows for now? As @cowwoc [mentionned](https://github.com/pytorch/kineto/issues/280#issuecomment-918747082), it is possible to profile/trace the CPU but trying to profile the GPU gives a CUPTI error. 

If that is the case, is there a release date scheduled? Looking at the different PRs and threads, it seems it has been worked on but temporarily left behind.

**Comment by AndreasKaratzas** [comment]
Windows version of the profiler still not working, and it's not just a backslash issue, my json file exported on Windows has not even got a proper structure. It's like it stopped printing before it was supposed to. Tested the same exact code on Ubuntu, and it worked like a charm.

**Comment by gcervantes8** [comment]
I think the issue should be reopened since profiling CUDA for Windows doesn't work. @aaronenyeshi

**Comment by kchawla-pi** [comment]
I face the same issue.

Pytorch: 10.13
CUDA: 12.0
Windows 11: 22H2

```python
    from torch.profiler import profile, record_function, ProfilerActivity
    with profile(activities=[ProfilerActivity.CUDA], use_cuda=True, profile_memory=True)as profile_results:
        with record_function("predict_breast_mask"):
            preds_breast = predict_breast_mask(subjects=preprocessed, base_save_path=disk_paths.save_root_dirpath)
```

Raises:
```red
AssertionError: Legacy CUDA profiling requires use_cpu=True
```

**Comment by SavinayShukla** [comment]
Please reopen this issue
Kineto Tracing still does not work on Windows.

**Comment by cfgfung** [comment]
> Please reopen this issue Kineto Tracing still does not work on Windows.

@guotuofeng @cloudhan Is this going to be reopened? Or is Kineto already fully functioning on Windows?

**Comment by zejun-chen** [comment]
Hi, @guotuofeng 

Is there any plan for supporting the windows kineto?

Thank you.

**Comment by zejun-chen** [comment]
Hi, @guotuofeng 

I find the kineto has been partly enabled for Windows but CUPTI has some issues working on Windows.

Thank you.
