### ISSUE TITLE
Is it possible to build with an already-installed fmt?

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/kineto#292]
I'm writing a [Spack](https://spack.io) package for kineto. Is it possible to use already-installed copies of fmt? I try to avoid relying on git submodules, especially when using a package manager.

P.S. Would anyone like to be listed as the official maintainer for the kineto package? You don't need to know much about Spack, it just gives us someone to ping when a user reports build issues or wants to modify the build recipe.

**Comment by cloudhan** [comment]
It seems to be possible, see https://github.com/pytorch/pytorch/blob/eb36f67dcc7000caa58fa4dfa9c089ce17c6d523/cmake/Dependencies.cmake#L1816
and https://github.com/pytorch/pytorch/blob/eb36f67dcc7000caa58fa4dfa9c089ce17c6d523/cmake/Dependencies.cmake#L1910

From the logic of https://github.com/pytorch/kineto/blob/d251e27882b77ec4625d962e64ff6b4fcfc9beb1/libkineto/CMakeLists.txt#L88-L92, you could wrap CMakeLists.txt into another CMakeLists.txt or just patch it, with
```
find_package(fmt REQUIRED)
set(FMT_SOURCE_DIR /a/correct/path)
```
prepended.

**Comment by adamjstewart** [comment]
I assumed `FMT_SOURCE_DIR` had to be the source code. Can it point to a compiled installation prefix?

**Comment by cloudhan** [comment]
I'm not quite sure about it. If `find_package(fmt REQUIRED)` succeed, then a `fmt` target should be defined. In this case, the whole `if(NOT TARGET fmt)` branch will be disabled. Then `FMT_SOURCE_DIR` will only be used in
```
set(FMT_INCLUDE_DIR "${FMT_SOURCE_DIR}/include")
```
to initialize include dir.

**Comment by adamjstewart** [comment]
It looks like it doesn't work. `FMT_SOURCE_DIR` must contain a `CMakeLists.txt` file, so it can't be the installation prefix.

P.S. Love the Ghost in the Shell profile pic!
