### ISSUE TITLE
Is it possible to obtain references of executed pytorch operation functions in profiler's logic?

### ISSUE THREAD

**Issue by tefantasy** [pytorch/kineto#317]
Hello,

I am developing an application based on pytorch. One essential step is to get the execution order of operations when backward propagation is performed, particularly for multi-device scenarios (i.e., model parallelism) since we observed this order could be non-deterministic. 

The visualized results produced by pytorch profiler appeals to me since it clearly shows the timing (and operation names) of CPU and CUDA activities, but I wonder if it is possible to directly get references of operation function objects (e.g., tensor.grad_fn) somewhere inside the profiler's logic? So that I could build the execution order automatically. I would really appreciate it if you could shed some light on this.

**Comment by gaoteng-git** [comment]
@tefantasy Do you mean finding each backward-op's corresponding forward-op?
I proposed this idea previously, but not sure how strong this requirement is in the community.
https://github.com/guyang3532/pytorch_profiler/issues/12

**Comment by tefantasy** [comment]
@gaoteng-git Many thanks for your reply. What I want is to correlate operators in backward pass (like AddmmBackward) with python side function or Module. 

The method you mentioned (correlate backward-op with forward-op, and then forward-op with python side Module) seems to be a possible way for now. I will explore more on it.

**Comment by gdankel** [comment]
We did discuss this. @ilia-cher and @ngimel do you recall what we landed on for this?

**Comment by aaronenyeshi** [comment]
This is added by @robieta via with_stack=True.
