### ISSUE TITLE
support of torch.cuda.nvtx.range_push() & torch.cuda.profiler.start()

### ISSUE THREAD

**Issue by TianhaoFu** [pytorch/kineto#318]
Hi, 

In pytorch 1.7 torch.autograd.profiler, we can insert NVTX marker through torch.cuda.nvtx.range_push().

Can torch.profiler also do that?

Thanks!

**Comment by cloudhan** [comment]
I have (informally) proposed it internally in Microsoft and we are going to discuss it with Facebook latter.

I'd like to add range/zone marker, via `push` and `pop`. And optionally get rid of context manager to avoid messing around with user code, that is, context manager inevitably introduce another level indention into user code.

**Comment by gdankel** [comment]
Sure, we should definitely continue to support nvtx so that e.g. Nsight Systems. Probably we should make it an activity type?

**Comment by jon-chuang** [comment]
Hello @aaronenyeshi, could you explain why this was marked as completed?

I do not see any support for tracing NVTX in kineto, in particular, it requires support for `CUpti_ActivityMarker2`, `CUPTI_ACTIVITY_KIND_MARKER`

**Comment by jon-chuang** [comment]
You can see how pytorch autograd profiler has a hacky way of processing these events here:

https://github.com/pytorch/pytorch/blob/105381ea1159eb025a580f008c78f2682caee930/torch/autograd/profiler.py#L904

**Comment by jon-chuang** [comment]
https://github.com/pytorch/kineto/blob/8378e801631475f7271f3688890a8f970ebf1017/libkineto/src/CuptiActivityProfiler.cpp#L699

In particular, `CUPTI_ACTIVITY_KIND_MARKER` is completely missing from the list of cupti activities that kineto processes 

How can I possibly view the kineto logs while running `KINETO_USE_DAEMON=1`?

**Comment by jon-chuang** [comment]
![image](https://github.com/pytorch/kineto/assets/9093549/8abb2f58-1b88-46dd-930e-e5d474b6968a)

Weirdly enough, the unexpected cuda events that are recorded on my workload is 0.

**Comment by jon-chuang** [comment]
Oh, I see, cupti itself does not even enable recording activity types outside of the ones listed, so they do not even show up as unexpected.
