### ISSUE TITLE
No results loaded with torch-tb-profiler when there isn't a profiler in the code

### ISSUE THREAD

**Issue by ManiadisG** [pytorch/kineto#334]
I have installed torch-tb-profiler and, when my code includes a profiler, the results of my experiments are displayed correctly in Tensorboard.
Example:
![image](https://user-images.githubusercontent.com/25967947/124389474-eb6cc280-dcef-11eb-8a3a-1fb231423db4.png)

However, if my code doesn't use a profiler, nothing is displayed and the spinner icon spins indefinately:

![image](https://user-images.githubusercontent.com/25967947/124389281-1a366900-dcef-11eb-8e80-cc2b23018324.png)

If I uninstall torch-tb-profiler, tensorboard again works as intended (though, of course, I can no longer view the profiler outcomes from experiments that do use it).

Is there a way to overcome this and allow for the visualization of both experiments that do and don't use a profiler?

System Information:

- Ubuntu 20.04
- Anaconda environment

Relevant package versions:

- pytorch 1.8.1
- tensorboard 2.5.0
- tensorboard-plugin-profile 2.4.0
- torch-tb-profiler 0.2.0

**Comment by guotuofeng** [comment]
duplicated with https://github.com/pytorch/kineto/issues/270
