### ISSUE TITLE
TensorBoard plugin blocks TensorBoard UI from fully loading

### ISSUE THREAD

**Issue by psybuzz** [pytorch/kineto#338]
Repro:
- In a fresh Python virtualenv, `pip install tensorboard torch-tb-profiler`
- Open TensorBoard (http://localhost:6006 by default)
- The UI under the header is blank, but the loading spinner rotates
![image](https://user-images.githubusercontent.com/2322480/124791363-d87d0c80-df00-11eb-8931-4d7619e208f7.png)
- In the DevTools network panel, the '/plugins_listing' request is stalled
- Eventually showing an error
![image](https://user-images.githubusercontent.com/2322480/124791476-f0ed2700-df00-11eb-9f0a-462dbc15aa0b.png)

On my machine, I tested this with
- tensorboard==2.5.0
- torch-tb-profiler==0.2.0

From a brief read, torch-tb-plugin's `is_active()` method seemingly issues blocking call to wait for data:
https://github.com/pytorch/kineto/blob/be239c044d2f4b62982e1ff64144097acd69f59a/tb_plugin/torch_tb_profiler/plugin.py#L69-L74

On the TensorBoard side, there have been a few reports from users who find TensorBoard responsive again after uninstalling torch-tb-plugin: https://github.com/tensorflow/tensorboard/issues/5076, https://github.com/tensorflow/tensorboard/issues/5111

TensorBoard's other builtin plugins are implemented with `is_active`s that either return quickly or are non-blocking.  Would it be possible for torch-tb-plugin to do something similar?

**Comment by EricWiener** [comment]
I'm also running into this issue with a docker image w/ tensorflow 2.5.0, tensorboard 2.5.0, and torch_tb_profiler 0.2.0.

**Comment by guotuofeng** [comment]
This is a known bug, we will fix it
