### ISSUE TITLE
Get message `There are not any runs in the log folder.` when there are runs

### ISSUE THREAD

**Issue by EricWiener** [pytorch/kineto#347]
The directory the tensorboard points to contains:
```
checkpoints
events.out.tfevents.1625863753.5728-desktop.11577.0
fit-training_step_and_backward.1625863814669.pt.trace.json
fit-validation_step.1625863794721.pt.trace.json
hparams.yaml
```

The tensorboard is displaying the logged data correctly, but `torch_profiler` says that there are no runs.

<img width="1910" alt="Screen Shot 2021-07-09 at 2 06 35 PM" src="https://user-images.githubusercontent.com/18071029/125136049-e37d9b80-e0be-11eb-9654-3f962d448566.png">

I installed with:
```
pip install -U git+https://github.com/pytorch/kineto.git@0332c84eea2382d45eac4278eaa51ac1a8f5701d#subdirectory=tb_plugin
```

**Comment by EricWiener** [comment]
Also, not sure if this is related, but I also get the warning
```
W0709 21:04:29.859560 140416021624576 security_validator.py:46] In 3.0, this warning will become an error:
Requires default-src for Content-Security-Policy
```

which didn't show up before installing `torch_tb_profiler`.

**Comment by EricWiener** [comment]
I made it work by switching to using tensorboard by creating symlinks for the log directories, but it seems like it should work either way

**Comment by guotuofeng** [comment]
@EricWiener , I tried use your file name one file named as fit-training_step_and_backward.1625863814669.pt.trace.json in one specific folder "~/empty2". Then I launched tensorboard with pytorch_profiler show successfully.

here is my start commands
```bash
tensorboard --logdir=~/empty2/ --bind_all
```

what's is your launching commands? would you please share us your traces files to myguo@microsoft.com

**Comment by EricWiener** [comment]
Sorry I'm not able to share the traces and it seems to be working now, so I'm gonna close the issue. Thank you for your help!
