### ISSUE TITLE
Is there a way to restrict the number of processes?

### ISSUE THREAD

**Issue by ManiadisG** [pytorch/kineto#348]
As I understand it, tb-profiler currently assigns the reading of each experiment (or .json profiler trace?) to a distinct process up to the maximum capacity of the local machine, so that the traces are loaded in parallel. However, that causes my machine to crash when I want to read multiple experiments. as it overloads my CPU and RAM.

Is there a way to restrict the maximum number of workers that tensorboard and profiler utilize? Or perhaps stick to single-worker non-parallel execution?

Note that, while CPU usage can be limited (e.g. via taskset), I could not find a way to limit the number of processes, which still overloads the RAM.

 ---------

System Information:

Ubuntu 20.04
Anaconda environment
Relevant package versions:

pytorch 1.8.1
tensorboard 2.5.0
tensorboard-plugin-profile 2.4.0
torch-tb-profiler 0.2.1

**Comment by gaoteng-git** [comment]
@guotuofeng Consider adding a switch(such as environment variable) to restrict number of parallel processes?
Or we may get number of CPU cores and just use half of cores in loading.
