### ISSUE TITLE
Why CUDA_SOURCE_DIR instead of CUDA_HOME?

### ISSUE THREAD

**Issue by aingo03304** [pytorch/kineto#36]
This is sort of nitpicking.

According to README of libkineto and `CMakeLists.txt`,
```
If CUDA_SOURCE_DIR is not set, libkineto will fail to build.
```
https://github.com/pytorch/kineto/blob/3c772487cb98c7758e055af4788a3c1274f02a4f/libkineto/CMakeLists.txt#L80-L83

However, the build script of PyTorch uses CUDA_HOME.
Why did you choose CUDA_SOURCE_DIR instead of CUDA_HOME? Is there any reason for this?

**Comment by ilia-cher** [comment]
(cc. @gdankel)

**Comment by gdankel** [comment]
> This is sort of nitpicking.
> 
> According to README of libkineto and `CMakeLists.txt`,
> 
> ```
> If CUDA_SOURCE_DIR is not set, libkineto will fail to build.
> ```
> 
> https://github.com/pytorch/kineto/blob/3c772487cb98c7758e055af4788a3c1274f02a4f/libkineto/CMakeLists.txt#L80-L83
> 
> However, the build script of PyTorch uses CUDA_HOME.
> Why did you choose CUDA_SOURCE_DIR instead of CUDA_HOME? Is there any reason for this?

No good reason, happy to change! @ilia-cher, how did you get the build working then? Do you explicitly set CUDA_SOURCE_DIR as well?

**Comment by gdankel** [comment]
@ilia-cher OK with changing this to CUDA_HOME I assume?

**Comment by ilia-cher** [comment]
that's fine, sure, we'll need to double check the pytorch cmake, but feel free to make the change
