### ISSUE TITLE
Use signal to trigger the profiling trace generation

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/kineto#406]
I saw there is support of signal API there to activate the trace generation. I am curious whether there is any example how to use it? I tried to send signal to the pytorch process(build with kineto enabled), but ended up with pytorch process terminated. Another question is whether we could get the application level activity. such as operator, if we only control the libkineto? Thanks.
cc @ilia-cher @gdankel

**Comment by gdankel** [comment]
Hi this is not enabled by default and currently you'll have to enable it via a config file option. Default config file location is in /etc/libkineto.conf but you can override this using the KINETO_CONFIG env var.

Adding the line
ENABLE_SIGUSR2=yes
should do it.

Let me know if it works for you.

**Comment by lly-zero-one** [comment]
Thanks, @gdankel  So if we also want to get the application(pytorch) level activity, can we do it without any instrumentation to user model code?

**Comment by gdankel** [comment]
Yes. There are currently some limitations however - you can't get call stacks or memory events for example. But planning to address this in time so that the same functionality is available with or without instrumentation.

**Comment by gdankel** [comment]
> Hi @gdankel It looks like the signal part could work. However, I encountered some issue of how to use it in my workflow. I am running pytorch(use_kineto=true) training flow, didn't instrument any profiler related code to trigger the libkineto_init, and want to get traces about the training code. I believe we need some way to trigger the [InitializeInjection](InitializeInjection) function. In OSS, the libkineto is statically compiled into torch lib. So which library should I use to set CUDA_INJECTION64_PATH in my scenario?
> 
> Another issue is that I didn't get pytorch level (such as operator) trace. All of the event/activity are from cuda internal. Here is the config:
> 
> ```
> ENABLE_SIGUSR2=yes
> ACTIVITIES_ENABLED=true
> ACTIVITIES_DURATION_SECS=3
> ACTIVITIES_DURATION_MSECS=1000
> ACTIVITIES_ITERATIONS=3
> ```

OK yes so this works internally, but it might not actually work with the current OSS version. You should be able to get GPU activities but I don't think you'll currently get PyTorch ops in the trace, even if you are able to trigger successfully.
I am currently refactoring the code and in the new version it should be doable... I think you need to stay tuned a little longer. By the way, this is an undocumented and unsupported feature as far as OSS goes, but we can look into supporting it better in a future release.

**Comment by lly-zero-one** [comment]
Thanks. I will look forward to the features.

**Comment by chaekit** [comment]
Hello @lly-zero-one ! We have landed a way for OSS version to trace host side activities as we do for internal workloads. These are our "prototype" features and expect it to be in 1.12. The only caveat is that it is guarded in compiler flag, and would require building from branch cut source. We may try to make it default for 1.12 but is not guaranteed. Let me know if you have concerns. cc: @chauhang

**Comment by lly-zero-one** [comment]
Hi @chaekit, can you elaborate the compiler flag we can use? also is there any example how to use it? Thanks in advance.

**Comment by aaronenyeshi** [comment]
Please take a look at Dynolog: https://github.com/facebookincubator/dynolog/blob/main/docs/pytorch_profiler.md#triggering-an-on-demand-trace
cc @briancoutinho
