### ISSUE TITLE
Operator View - Blank Screen

### ISSUE THREAD

**Issue by ztyree42** [pytorch/kineto#423]
Noob here, just trying to go through the documentation for the pytorch_profiler and I can't access the Operator View. When I click it I get a flicker and it _seems_ like maybe the view is showing momentarily but it's too quick to be sure. Regardless, I'm quickly met with a blank screen. The other views all work as advertised.

**Comment by guotuofeng** [comment]
@ztyree42 are there any repro steps? I screenshot would be much more helpful as well.

**Comment by ztyree42** [comment]
Here's my code:

```
import torch
import torch.nn
import torch.optim
import torch.profiler
import torch.utils.data
import torchvision.datasets
import torchvision.models
import torchvision.transforms as T

transform = T.Compose(
    [T.Resize(224),
     T.ToTensor(),
     T.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
train_set = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(train_set, batch_size=32, shuffle=True)

with torch.profiler.profile() as prof:
    pass

device = torch.device("cuda:0")
model = torchvision.models.resnet18(pretrained=True).cuda(device)
criterion = torch.nn.CrossEntropyLoss().cuda(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
model.train()

def train(data):
    inputs, labels = data[0].to(device=device), data[1].to(device=device)
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.profiler.profile(
        schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=2),
        on_trace_ready=torch.profiler.tensorboard_trace_handler('./log/resnet18'),
        record_shapes=True,
        with_stack=True
) as prof:
    for step, batch_data in enumerate(train_loader):
        if step >= (1 + 1 + 3) * 2:
            break
        train(batch_data)
        prof.step()  # Need to call this at the end of each step to notify profiler of steps' boundary.
```

It's the snippet from the Pytorch docs on the profiler along with this line

`with torch.profiler.profile() as prof:
    pass
`

which is a hack to fix the bug with Nvidia Driver 465.

All I've done is run that code sample and then open Tensorboard from the command pallette. Here's what I'm looking at

![image](https://user-images.githubusercontent.com/17054909/133530447-6a31ad25-bcf5-456f-b1d6-bfbff1bfcc42.png)

**Comment by guyang3532** [comment]
@ztyree42 Can you see other views? overall view? in the Tensorboard in VSCode? Can you show the log printed in TERMINAL?

**Comment by ztyree42** [comment]
VSCode 1.60.1, Python 3.9
I can see the all of the other views including the Overview. All of this is Tensorboard integrated in VSCode run from the command palette. 

Here are the logs, I've shortened them for readability, there are about a thousand lines of 
```
Error 2021-09-15 17:30:01: W0915 17:30:01.915851 140307475097344 event_parser.py:80] 1 Runtime with external id 8520 don't correlate to any operator!
```
this style Error

```
Error 2021-09-15 17:30:01: W0915 17:30:01.915851 140307475097344 event_parser.py:80] 1 Runtime with external id 8520 don't correlate to any operator!

Error 2021-09-15 17:30:02: INFO:pytorch_profiler:Run resnet18 loaded

Error 2021-09-15 17:30:02: INFO:pytorch_profiler:Add run resnet18

Error 2021-09-15 17:30:02: WARNING:tensorboard:In 3.0, this warning will become an error:
Requires default-src for Content-Security-Policy
```

**Comment by guyang3532** [comment]
Are the installed packages pytorch == nightly and torch-tb-profiler == 0.2.1 ? If they are, it's a known bug. 
You may downgrade the pytorch version to 1.9 or install the latest torch-tb-profiler from source code at https://github.com/pytorch/kineto/tree/plugin/vnext
install command:
cd tb_plugin
pip install .

**Comment by ztyree42** [comment]
Ah, yes they are :/ unfortunately I'm on driver 465 and need the nightly
build to address another cudnn bug. Thanks for your help!

**Comment by guyang3532** [comment]
Pytorch nightly can work with latest torch-tb-profiler. You can install it from source code.
