### ISSUE TITLE
Chrome tracing file can't tell async task with sync task

### ISSUE THREAD

**Issue by gaoteng-git** [pytorch/kineto#43]
Through reviewing the code of pytorch profiler and kineto, I found in the case of async task, there is an inconsistency on assigning thread id to FunctionEvent and ClientTraceActivity. 

1.	When running with @torch.jit.script, torch.jit.fork and torch.jit.wait, such as the first example code in [Dynamic Parallelism in TorchScript](https://pytorch.org/tutorials/advanced/torch-script-parallelism.html), the “example” function is an async task, its start_thread_id and end_thread_id in profiling result will be different.
In [torch/autograd/profiler.py](https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py), I could see it carefully handles this kind of event with checking “is_async”, it does not attach children and does not calculate self time on it.
However, in the dumped chrome tracing file (with kineto enabled), I could only see “example” as a normal “Operator” with “ph” as “X”. There is no message showing it is an async task. It just assign [end thread's id](https://github.com/pytorch/pytorch/blob/0c313564af6173d54b393ae0b70cf2cb0db5a5c8/torch/csrc/autograd/profiler_kineto.cpp#L73) to "tid".
My concern: Will regarding the async tasks simply as sync tasks have potential risk? If we simply regard async tasks as sync tasks, will they have risk to overlap (cross, not contain) with each other in chrome tracing UI view? 
And if we can’t tell async tasks with sync tasks, our [tb_plugin](https://github.com/pytorch/kineto/tree/master/tb_plugin) may can’t achieve same expected result as pytorch autograd profiler. For example, we will calculate self time of it because we can’t know it is actually an async task.

Another two tiny issues:

2.	There are 3 thread id:
    2.1	In profiler_kineto.cpp, the thread id is got from at::RecordFunction::currentThreadId([start](https://github.com/pytorch/pytorch/blob/0c313564af6173d54b393ae0b70cf2cb0db5a5c8/torch/csrc/autograd/profiler_kineto.cpp#L168), [end](https://github.com/pytorch/pytorch/blob/0c313564af6173d54b393ae0b70cf2cb0db5a5c8/torch/csrc/autograd/profiler_kineto.cpp#L204)). 
    2.2	In chrome tracing file, the “tid” is [real pthread id](https://github.com/pytorch/pytorch/blob/0c313564af6173d54b393ae0b70cf2cb0db5a5c8/torch/csrc/autograd/profiler_kineto.cpp#L73)
    2.3	In chrome tracing file, the id in “thread_name” is got from [ChromeTraceLogger::renameThreadID](https://github.com/pytorch/kineto/blob/a69864a7bbaeaaef7c3641da18de0ed1312ed2f7/libkineto/src/output_json.cpp#L61). 
Maybe the 2.1 and 2.3 could be made more consistent?

3.	The [Ln56](https://github.com/pytorch/pytorch/blob/0c313564af6173d54b393ae0b70cf2cb0db5a5c8/torch/csrc/autograd/profiler_kineto.cpp#L56) in profiler_kineto.cpp seems redundant, only keep [Ln73](https://github.com/pytorch/pytorch/blob/0c313564af6173d54b393ae0b70cf2cb0db5a5c8/torch/csrc/autograd/profiler_kineto.cpp#L73) is enough.

**Comment by gdankel** [comment]
@gaoteng-git for 1) what do you think is the best option in terms of user experience? I agree we have to do *something* as overlapping regions in Chrome traces will mess up the rendering, and is in any case wrong.

For 2) I believe RecordFunction::currentThreadId is needed for looking up thread events on the pytorch side, but on the other hand pthread id is used by CUPTI. I will remove ChromeTraceLogger::renameThreadID and use linux tid instead. I will check whether we can remove pthread id - CUPTI supports both linux tid and pthread ID, but I observed a large perf hit using linux tid.

Perhaps we can also use linux tid for 1) (or other system-specific tid - falling back to the current approach if unimplemented) and pass that through to Kineto.

**Comment by gaoteng-git** [comment]
@gdankel For 1) A possible option is to use two "Instant Events" with "ph":"i" to mark the begin and end of an async task, and add a new category of "Flow Events" to link the above two.
Another conservative way is just add a field to "args", with "name" such as "start thread id", then our plugin could differentiate async task with sync task.
I don't knowi its priority because I'm not sure whether aysnc tasks could really "cross" each other in real running case, such as:
op1 starts with "tid:1, ts:100" and ends with "tid:2, ts:150";
op2 starts with "tid:1, ts:120" and ends with "tid:2, ts:160".
