### ISSUE TITLE
libkineto::api().activityProfiler() returns NULL value

### ISSUE THREAD

**Issue by maharishib** [pytorch/kineto#445]
I'm not able to use activity profiler as libkineto::api().activityProfiler() returns NULL value. 
The cause for this is InitializeInjection in init.cpp is not getting called. I tried setting the value of CUDA_INJECTION64_PATH env variable but it didn't have any effect.
Any suggestions on fixing this.
Thanks.

**Comment by briancoutinho** [comment]
is this using pytorch @maharishib or just using the library stand alone? Looks like you need to do an initialization of the activityprofiler initProfilerIfRegistered()
