### ISSUE TITLE
TensorBoard Overview Missing and Operator view crash for GPU only trace

### ISSUE THREAD

**Issue by aaronenyeshi** [pytorch/kineto#446]
When launching a GPU-only trace on the TensorBoard plugin (on VS Code), the `Overview` View looks incorrect and the `Operator` view will crash. The `Trace` and `GPU Kernel` Views work great!  I've been able to reproduce this issue using TorchBench runs.

These are the steps to reproduce the issue:

1. git clone https://github.com/pytorch/benchmark
2. Install any dependencies:
    - Use python 3.7 and install torch, torchvision, torchtext (see details here: https://github.com/pytorch/benchmark#using-pre-built-packages)
3. Run: `python run.py -d cuda --profile densenet121` to generate a GPU-only trace file to local directory `./logs/`
4. Open the trace on TensorBoard in VS Code, and see tabs `Overview` and `GPU Kernel`

Here are screenshots for a trace:
Overview View:
![image](https://user-images.githubusercontent.com/17602366/137528353-191cb26f-0c07-4c60-8faf-4bf22449c489.png)
Operator View:
![image](https://user-images.githubusercontent.com/17602366/137528475-1fd7c7d8-ded1-4887-a9ae-e1656e42251a.png)
GPU Kernel View:
![image](https://user-images.githubusercontent.com/17602366/137528516-6c4edb76-05d7-4ba2-b9e4-2a342f72dcab.png)
Trace View:
![image](https://user-images.githubusercontent.com/17602366/137528555-e5ad1ca8-231b-4279-b42e-628be4bfc4fa.png)

+ CC @gdankel , @eircfb , @xuzhao9, @robieta

**Comment by guotuofeng** [comment]
@aaronenyeshi, would you please help provide more context information? 
for example, the PT version, plugin version? it would be better if the trace file can be shared as well.

**Comment by guotuofeng** [comment]
@aaronenyeshi , you can use the 0.3.1 since you are using pytorch nightly build
