### ISSUE TITLE
getSMCount() does not work for Turing and later

### ISSUE THREAD

**Issue by btian** [pytorch/kineto#478]
https://github.com/pytorch/kineto/blob/main/libkineto/src/CuptiActivityApi.cpp#L66

Why not use CUDA device properties instead? I.e.,

```
  int nDevices;
  cudaError_t error_id = cudaGetDeviceCount(&nDevices);
  if (error_id != cudaSuccess) {
    return -1;
  }
  for (int i = 0; i < nDevices; ++i) {
    cudaDeviceProp prop;
    error_id = cudaGetDeviceProperties(&prop, i);
    if (error_id != cudaSuccess) {
      return -1;
    }
    return prop.multiProcessorCount;
```

**Comment by gdankel** [comment]
I think this function can be removed - we do use CUDA device properties and this is just a left-over.

**Comment by aaronenyeshi** [comment]
Closing since this has been fixed. 
https://github.com/pytorch/kineto/blob/main/libkineto/src/CudaDeviceProperties.cpp#L85
