### ISSUE TITLE
Error while running tutorial example

### ISSUE THREAD

**Issue by tranhoangkhuongvn** [pytorch/kineto#507]
Hi,

I received this error while running the code example in the "PYTORCH PROFILER WITH TENSORBOARD" with context manager
`[W CPUAllocator.cpp:306] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event`

If I try the non-context manager I receive a segmentation fault (core dumped) error

I ran this on Ubuntu 20.04.3 LTS and pytorch version 1.11.0a0+gitb27dfa7
GPU 3090 RTX

Tutorial link: https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html
Thanks
Khuong

**Comment by robieta** [comment]
What do you mean by "non-context manager"?

**Comment by guotuofeng** [comment]
@robieta, the non-context manager is meaning
![image](https://user-images.githubusercontent.com/817030/150625966-db6265e1-e965-4d67-b9e7-467a1186ba3e.png)
in https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html?highlight=tensorboard

@tranhoangkhuongvn is the segment fault related to  https://github.com/pytorch/pytorch/issues/69443?

**Comment by aaronenyeshi** [comment]
Please re-open an issue if this is still observed.
