### ISSUE TITLE
Clarification about "kernel" category and recommended improvements

### ISSUE THREAD

**Issue by blazejdolicki** [pytorch/kineto#514]
Hello,

I'm working with a dataset with 300k examples that takes about 1 hour to complete one epoch which seems to me slower than expected, so I tried to find possible bottlenecks (e.g. dataloader). Today I found out about profiling with kineto tensorboard which appears to be exactly what I needed, thanks for implementing it!

When using it, this is the graph I get, clearly the dataloader is not the problem as 95% of the runtime falls into the "Kernel" category.
![image](https://user-images.githubusercontent.com/29718307/152162240-8ed51ac9-e01a-4b7d-86fd-0f830ddc2029.png)

This name is a little mysterious, is it synonymous to "GPU"? My understanding is that with this output, to decrease training time I can do the usual GPU-related steps:
* get a better GPU
* increase batch size
* use more GPUs
* use mixed precision

Is my understanding correct? Or are there other steps I should take to speed up the training loop?

**Comment by guotuofeng** [comment]
yes, you are correct. Kernel means GPU related operation launched by underlying PyTorch operators. 

What's the general recommendation with your chrome trace file by Tensorboard UI?

**Comment by blazejdolicki** [comment]
Thank! The recommendation in the UI is to use mixed precision I believe.

**Comment by guotuofeng** [comment]
> Thank! The recommendation in the UI is to use mixed precision I believe.

could you please let us know whether the batch size and mix precision helps or not?
