### ISSUE TITLE
No GPU/CUDA

### ISSUE THREAD

**Issue by Alobal** [pytorch/kineto#564]
Hi

When I test the example program(resnet50), tensorboard only show CPU and Other, however the code is running on cuda .

![image](https://user-images.githubusercontent.com/35487993/158385801-b8f29040-0790-4082-8c79-3f4da94855fe.png)

When I use pytorch profiler in my model , it also output no GPU SUMMARY too. 

I don't know what's wrong.

my environment: pytorch1.10.1+cu113, win10,  python3.8.10

Thank you for your help!

**Comment by aaronenyeshi** [comment]
Hi @Alobal, do you know when this issue started? (pytorch src changes, kineto update, etc)

**Comment by Alobal** [comment]
Sorry, I just used  it yesterday, so I do not know what happened in the past versions.

**Comment by erasromani** [comment]
I'm running into this same issue. Has anyone been able to resolve it?

**Comment by Alobal** [comment]
I find the issue is only happened on Windows, when I use Ubuntu , there is no problem.

**Comment by cbjuan** [comment]
I'm experiencing something similar in Ubuntu. 

In the overview, I get there is a GPU, but it does not show the "GPU Summary" section (the GPU is reporting more data, I also get the memory view for the GPU).

<img width="897" alt="Screenshot_2022-06-21_at_12_59_55" src="https://user-images.githubusercontent.com/2938045/174789226-6082ea56-18b1-4c75-86ad-f6cb359ca2b5.png">


Info:
```
OS: Ubuntu 20.04 
torch.__version__: 1.11.0+cu113
torch.version.cuda: 11.3
torch.backends.cudnn.version(): 8200
torch.cuda.get_device_name(0): Tesla V100-PCIE-16GB
torch.cuda.get_device_properties(0): _CudaDeviceProperties(name='Tesla V100-PCIE-16GB', major=7, minor=0, total_memory=16160MB, multi_processor_count=80)
```

**Comment by nitsanh** [comment]
Hi, I was having the same issue, running with python 3.8.10 and the new torch 1.12.0. Before upgrading to torch 1.12.0 everything worked fine. Downgrading back to torch 1.11.0 solved the problem for me.

**Comment by yangyanli** [comment]
I am experiencing similar (or the same?) issue with pytorch 1.12 as described by @cbjuan .

Moreover, I noticed a warning:
```
[W kineto_shim.cpp:337] Profiler is not initialized: skipping step() invocation
```
which was not there with pytorch 1.10.

**Comment by aaronenyeshi** [comment]
This should be fixed with next Tensorboard plugin release. @chauhang - do you know when there will be another tb_plugin release?

**Comment by NouamaneTazi** [comment]
Possibly related issue https://github.com/pytorch/kineto/issues/659
