### ISSUE TITLE
"fwd_bwd_correlation" button doesn't exist

### ISSUE THREAD

**Issue by danielsnider** [pytorch/kineto#578]
The "fwd_bwd_correlation" button doesn't exist.

Your [README](https://github.com/pytorch/kineto/blob/main/tb_plugin/README.md) talks about a really cool feature that's not working for me when I use your [sample.pt.trace.json](https://github.com/pytorch/kineto/blob/main/tb_plugin/samples) referred to in the [README](https://github.com/pytorch/kineto/blob/main/tb_plugin/README.md).

From [README](https://github.com/pytorch/kineto/blob/main/tb_plugin/README.md):
> When you select the top-right corner's "Flow events" to "fwd_bwd_correlation", you can see the relationship between forward operator and its launched backward operator. Note: Only the backward operator's direct launching forward operator will be connected by line, its ancestor operators which call this operator as child will not be connected.

Yours:
![image](https://user-images.githubusercontent.com/1737560/162361350-39bf0203-74a8-4b7d-98ed-9afb76791233.png)
![image](https://user-images.githubusercontent.com/1737560/162361358-b91ed729-ceb9-4612-989f-b5ce46b20b35.png)

Mine:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/1737560/162361306-daed919c-baff-4461-8f56-c10d7635148c.png">

I uncompressed the given sample [worker0.1623143089861.pt.trace.json.gz](https://github.com/pytorch/kineto/blob/main/tb_plugin/samples/resnet50_num_workers_0/worker0.1623143089861.pt.trace.json.gz) and I didn't find the string "fwd_bwd" there. Perhaps the sample file just doesn't have it?

I'm running the code from source:

```
commit f4e6fda4ea8d1a458dc16ab4650966fcd16ce3ba (origin/main, origin/HEAD, main)
Date:   Thu Apr 7 10:33:00 2022 -0700
```

With `Python 3.8.10` , Ubuntu 20.04 and I have this [pip freeze output](https://gist.github.com/danielsnider/1d415d05059123ddc1687524ac5f5d7f).

Thanks for this great profiler tool! This is a rather minor issue, but is of interest to me.

All the best,
Daniel

**Comment by aaronenyeshi** [comment]
This feature, fwd_bwd links, has been added back in https://github.com/pytorch/pytorch/pull/102424.
