### ISSUE TITLE
"Operator" view doesn't show Host/Device, only Host when all operations are performed on GPU?

### ISSUE THREAD

**Issue by ldorigo** [pytorch/kineto#591]
Hi, in the overview it shows that I have a GPU enabled :

![Screenshot_20220422_142212](https://user-images.githubusercontent.com/8631181/164713423-ee634087-0d8f-420a-98af-88085486256a.png)

However in the "Operator" view it shows only "Host" time, no "Device" time:

![Screenshot_20220422_142422](https://user-images.githubusercontent.com/8631181/164713761-d4907a3e-fa10-4eed-9bd7-4c7e25153d21.png)

Looking at the numbers, it seems like here the "Host" is the GPU, not CPU as I'd expect? Is this normal behaviour?

**Comment by aaronenyeshi** [comment]
Hi, thank you for the issue, can you please check if you are still reproducing the issue? Some event type names have recently been arranged.

**Comment by yangyanli** [comment]
Same issue here with pytorch 1.11 and 1.12, 1.10 works well though.

**Comment by aaronenyeshi** [comment]
Fixed in https://github.com/pytorch/kineto/pull/674
