### ISSUE TITLE
Trace view is empty, trace too large?

### ISSUE THREAD

**Issue by maximilian-tech** [pytorch/kineto#595]
Hi,

one epoch of my network creates a trace.json with 2.2GB size and 62_475_015 lines.
The trace was collected with the default settings.
The trace view is empty with no data shown.

Is the trace too large to be viewed with this plugin?
What are "normal" trace sizes?

Thanks!

**Comment by robieta** [comment]
Can you check to see if it will load in `chrome://tracing`? And do you see anything in the TensorBoard process logs that might be relevant?

If you can distill the issue down to a standalone repro I can take a look.

**Comment by maximilian-tech** [comment]
```chrome://tracing``` reports a ```Error while loading file: [object ProgressEvent]```.
The TensorBoard log shows nothing.
[One issue suggest](https://github.com/google/trace-viewer/issues/298) that it actually might be linked to a trace being too large. I try the trace viewer of [https://ui.perfetto.dev/#!/viewer](https://ui.perfetto.dev/#!/viewer) at the moment, but also hangs.

**Comment by robieta** [comment]
Hmm. Very curious. Chrome trace is known to be limited, but I thought Perfetto was supposed to scale better. CC @chaekit

**Comment by maximilian-tech** [comment]
A quick question: is it possible to view the generated traces with Perfetto? I try to load the sample traces but afterloading nothing is shown.

Would it be helpful if I share the large trace?

**Comment by chaekit** [comment]
yeah 2.2GB will most likely go over Chrome trace limit. for Perfetto, loading it on ui.perfetto.dev will load it on Chrome which runs into browser tab memory limit. 

there is a way to run this off of Chrome which is detailed here https://perfetto.dev/docs/visualization/large-traces, and should support bigger traces
