### ISSUE TITLE
`tb_plugin/examples/datapipe_example.py` outdated

### ISSUE THREAD

**Issue by msaroufim** [pytorch/kineto#604]
There's a few lines in this file that are now outdated

`import torchvision.prototype.models as models` does not exist

`    trainset = Cifar10().to_datapipe(root='./data', decoder=pdatasets.decoder.raw)` where `Cifar10()` expects to be passed in a `root` argument directly

Could be a couple more too

**Comment by aaronenyeshi** [comment]
Thank you for catching this, please feel free to submit a patch and we can help merge, or we will get back to you.

**Comment by msaroufim** [comment]
I chatted with @NicolasHug about this offline, given that this example leverages `prototype` features there is no expectation of backwards compatibility so this example will continue breaking until datapipes are promoted out of prototype. So for now I guess we can add a notice at the top of the code. I'll write something now

**Comment by aaronenyeshi** [comment]
Sounds good to me!
