### ISSUE TITLE
Tensorboard: No Runs Found

### ISSUE THREAD

**Issue by matrix97317** [pytorch/kineto#605]
![image](https://user-images.githubusercontent.com/76250408/170475808-434ff919-9d5d-4e69-bf00-29b445c9ea90.png)
![image](https://user-images.githubusercontent.com/76250408/170475865-8bd208de-6d38-40f3-9076-ffa9b98315ff.png)

**Comment by fengjinyuan** [comment]
torch: 1.10
torch_tb_profiler: 0.4.0
use code: tb_plugin/examples/resnet50_ddp_profiler.py

**Comment by aaronenyeshi** [comment]
Thanks for reporting, some of the examples are not working, we will investigate.
