### ISSUE TITLE
Windows paths not properly handled leading to decode error

### ISSUE THREAD

**Issue by robieta** [pytorch/kineto#617]
There is a `sanitizeStrForJSON` method in Kineto, however it is only applied to some internal cases. When the profiler passes a windows path (e.g. `foo\\bar\\baz`) the correct json serialization is `foo\\\\bar\\\\baz`, however the kineto json exporter does not perform this escaping. This leads to an invalid trace that fails to load due to

`json.decoder.JSONDecodeError: Invalid \escape:`

**Comment by jxtps** [comment]
This is a very frustrating bug while trying to debug what's going wrong with my profiling in a mixed Linux & Windows environment, would be fantastic if @robieta's suggestion could be made reality.

**Comment by aaronenyeshi** [comment]
@davidberard98 fixed this issue in https://github.com/pytorch/kineto/pull/754
