### ISSUE TITLE
Mapping CUDA operations to `nn.Module`  

### ISSUE THREAD

**Issue by sudomaze** [pytorch/kineto#636]
About a year ago, I came across PyTorch Profiler and shared my thoughts on this issue (https://github.com/pytorch/pytorch/issues/63159). I talked to someone from the PyTorch team about a certain point I mentioned in the issue. The ability to visualize the mapping of CUDA operations shown on the `tensorboard` to `nn.Module` components and, even better, show the code lines to ease of tracing.

From looking into this issue (https://github.com/pytorch/kineto/issues/342), it seems that there is a similar idea floating around. I wondered if this idea is under development or planned to be worked on in a future release?

**Comment by robieta** [comment]
It's actually landed. Search "Module view" in https://github.com/pytorch/kineto/tree/main/tb_plugin

**Comment by sudomaze** [comment]
That's awesome! I was planning to contribute by working on this feature. I will try to test it out sometime soon and share my feedback. Thanks!
