### ISSUE TITLE
[Low Pri] Update to C++ 17

### ISSUE THREAD

**Issue by briancoutinho** [pytorch/kineto#650]
Adding this issue as a placeholder for updating the C++ std supported in Kineto code.

Will adding a PR where we have commented out code to match C++ 11 standard used here. After this is migrated to C++17 we can uncomment the code.

Here is a related issue of migrating pytorch to C++ 17 as well. We should update Kineto once pytorch has completed it's migration
https://github.com/pytorch/pytorch/issues/56055

**Comment by aaronenyeshi** [comment]
This is completed, thanks!
