### ISSUE TITLE
Diff 2 traces

### ISSUE THREAD

**Issue by msaroufim** [pytorch/kineto#655]
My workflow when using the PyTorch profiler is often to have some baseline to which I'm comparing some updated code. In some cases the updated code works and I want to know why and in other cases it makes things worse and I also want to understand why.

So far I zoom in and out a bunch to eyeball some differences but that whole process is time consuming

**Comment by aaronenyeshi** [comment]
Recently open sourced HTA github repo has a new tool to help diff two traces: https://github.com/facebookresearch/HolisticTraceAnalysis/blob/main/examples/trace_diff_demo.ipynb

**Comment by msaroufim** [comment]
Cool! Thank you!
