### ISSUE TITLE
`kernel` vs `Kernel` category

### ISSUE THREAD

**Issue by NouamaneTazi** [pytorch/kineto#659]
It seems that after installing the nightly Pytorch, running the profiler now puts kernels in `kernel` category (lowercase k) instead of the previous `Kernel` category which causes kernels not to show up in the trace correctly.
Renaming all `kernel` back to `Kernel` in the produced trace did fix the issue for me
```
  {
    "ph": "X", "cat": "kernel", "name": "void at::native::(anonymous namespace)::ComputeFusedParamsCUDAKernel<c10::Half>
     ...
},
```
```
  {
    "ph": "X", "cat": "Kernel", "name": "void at::native::(anonymous namespace)::ComputeFusedParamsCUDAKernel<c10::Half>
     ...
},

**Comment by seelam** [comment]
I have the same problem, any update on this?

**Comment by aaronenyeshi** [comment]
Hi, thank you for your report. Could you please share a link or screenshot of the traces that do not show up correctly? Which tools are having trouble processing lowercase 'kernel'?

**Comment by seelam** [comment]
For me it is tensor board.

**Comment by aaronenyeshi** [comment]
The Tensorboard issue was fixed awhile ago, but it looks like we haven't released a new Tensorboard plugin package in awhile. I've asked the tb_plugin team on how to create a new package for TB. In the meantime, I've opened a diff that should revert back to legacy "Kernel" cat name. https://github.com/pytorch/kineto/pull/674
