### ISSUE TITLE
Release new tb_plugin package

### ISSUE THREAD

**Issue by aaronenyeshi** [pytorch/kineto#675]
@guotuofeng @guyang3532 @gaoteng-git @chauhang 

Would it be possible to release a new Tensorboard Plugin package? OSS users of Tensorboard are running into an issue where Tensorboard expects kernels to have category "Kernel" instead of "kernel".

This was fixed in https://github.com/pytorch/kineto/pull/593, but no new packages for Tensorboard have been release since then.

What is the procedure to release the new TB version with latest tb_plugin patches? 

As a workaround, I am reverting back to "Kernel". https://github.com/pytorch/kineto/pull/674

**Comment by fxmarty** [comment]
Please make a release to fix https://github.com/pytorch/kineto/issues/679

**Comment by aaronenyeshi** [comment]
This is now resolved, torch_tb_profiler v0.4.1 has been released to Pypi : https://pypi.org/project/torch-tb-profiler/0.4.1

**Comment by fxmarty** [comment]
Thank you for the quick fix!
