### ISSUE TITLE
[tb plugin] Trace view empty, Lightning view missing

### ISSUE THREAD

**Issue by juanigp** [pytorch/kineto#695]
Hello, I am new to the pytorch profiler, seems to be a really useful tool. 

I am using pytorch-lightning for my jobs, and passing a default `pytorch_lightning.profilers.PyTorchProfiler` object to the `pytorch_lightning.trainer.trainer.Trainer` constructor. 

I can see the "Normal" Overview, Operator, GPU Kernel, and Memory views for my resulting .json profiles, but the Trace view is empty. However, I can properly load and view the file in `chrome://tracing/`.

I am also completely missing the Lightning view from the dropdown menu.

This is my setup:
torch=1.13.0
pytorch-lightning=1.7.6
torch-tb-profiler=0.4.0
tensorboard=2.11.0

I attach one of my traces that work in `chrome://tracing/` but not in the Trace view:
[example.pt.trace.json.gz](https://github.com/pytorch/kineto/files/10073932/example.pt.trace.json.gz)

Thanks in advance!

**Comment by schmidt-jake** [comment]
I am also experiencing this issue. The lightning and distributed views are missing; the trace view has an incorrect x-axis scale, and the overview view does not display the correct number of steps per worker.

This seems to be a regression in torch 1.12. Downgrading to 1.11 seems to fix the issue, but this obviously isn't ideal...

**Comment by aaronenyeshi** [comment]
Hi, thanks for reporting the issue. A new torch-tb-profiler v0.4.1 has been released, could you please give it a try: https://pypi.org/project/torch-tb-profiler/0.4.1

**Comment by schmidt-jake** [comment]
v0.4.1 works for me! Thank you!!
