### ISSUE TITLE
How can I capture cudaEventRecord?

### ISSUE THREAD

**Issue by xmty777** [pytorch/kineto#737]
I want to capture cudaEventRecord in the trace, while it was filtered out in [#543 ](https://github.com/pytorch/kineto/pull/543)
I wonder if there is an easy way for me to capture it in pytorch profiler, or only rebuild pytorch? Thanks a lot!

**Comment by briancoutinho** [comment]
@aaronenyeshi any ideas why these were blacklisted. Curious if we can maybe configure this in an env variable or something?

**Comment by briancoutinho** [comment]
@aaronenyeshi any ideas why these were blacklisted. Curious if we can maybe configure this in an env variable or something?

**Comment by aaronenyeshi** [comment]
@chaekit may have more context on this blacklist. @xmty777 feel free to open a PR that enables them via env var. 

You can also build your own local pytorch, and comment out these lines: https://github.com/pytorch/kineto/blob/main/libkineto/src/CuptiActivityProfiler.cpp#L363 , in the path: `pytorch/pytorch/third_party/kineto/libkineto/src/CuptiActivityProfiler.cpp`.

**Comment by aaronenyeshi** [comment]
Workaround provided, closing this now.
