### ISSUE TITLE
How can I get detailed aten::op name like add.Tensor/abs.out?

### ISSUE THREAD

**Issue by Hurray0** [pytorch/kineto#742]
I wonder if I could trace detailed op name like add.Tensor、add.Scalar、sin.out、abs.out
Currently the profiler only gives me add/sin/abs, etc.

Is there a method to acquire detailed dispatched op name?

**Comment by aaronenyeshi** [comment]
You should be able to see the ops you mentioned in the trace file. Could you please share more details on what you expect, and what you actually see?
