### ISSUE TITLE
torch-tb-profiler doesn't support HDFS file system

### ISSUE THREAD

**Issue by yundai424** [pytorch/kineto#766]
Hi team, we notice that torch TB profiler plugin doesn't currently support HDFS https://github.com/pytorch/kineto/blob/main/tb_plugin/torch_tb_profiler/io/file.py#L66 . Right now only local FS, S3, GS and azure blob are allowed.

We would like to have this support added (iiuc the only thing needed is to implement it and register) as our profiling result is stored on HDFS.

**Comment by aaronenyeshi** [comment]
Feel free to add the changes needed to support HDFS. We can help review the changes.

**Comment by yundai424** [comment]
@aaronenyeshi sorry for the late response. I've added the changes. Would appreciate it if you could help to review https://github.com/pytorch/kineto/pull/793 Thanks!

**Comment by aaronenyeshi** [comment]
Thanks for landing the fix, closing this now.
