### ISSUE TITLE
comm_node.kernel_ranges is only avalible for Gloo?

### ISSUE THREAD

**Issue by jlijian3** [pytorch/kineto#797]
https://github.com/pytorch/kineto/blob/cc2e4834cb0236077f3b013d5df9a38747592ea8/tb_plugin/torch_tb_profiler/profiler/event_parser.py#L191C1-L192C1

**Comment by aaronenyeshi** [comment]
Please feel free to submit any PRs to fix the issue!

**Comment by aaronenyeshi** [comment]
https://github.com/pytorch/kineto/pull/813
