### ISSUE TITLE
The content of CMakeLists.txt in the test folder is missing?

### ISSUE THREAD

**Issue by zhuzhenxxx** [pytorch/kineto#803]
The content of CMakeLists.txt in the test folder is missing?

**Comment by fwenguang** [comment]
I also want to konw how to build and run the TEST files in test folder? @aaronenyeshi

**Comment by aaronenyeshi** [comment]
Hi, sorry about this. Currently our tests are run internally, and the CMakeLists.txt for our tests directory is incomplete: https://github.com/pytorch/kineto/blob/main/libkineto/test/CMakeLists.txt#L6.

We are open to the open source contributions to get this running in OSS. Currently the Github CI only builds libkineto, but does not test it, would be great to get Github CI running tests too. https://github.com/pytorch/kineto/blob/main/.github/workflows/libkineto_ci.yml#L56

**Comment by aaronenyeshi** [comment]
Added in https://github.com/pytorch/kineto/pull/869
