### ISSUE TITLE
How does kineto work actuallly?

### ISSUE THREAD

**Issue by stricklandye** [pytorch/kineto#847]
Hello, everyone. 
I took a quick look at the source code of kineto and it seems the most important part of kineto is [CUPTI](https://docs.nvidia.com/cupti/r_main.html#r_main). I am curious how does kineto work and I have tried some examples of CUPTI. I have some questions hope someone could give me some insights.
1. How does kineto get pytroch functions name?
From my short experience of CUPTI programming, I knew I could get CUDA runtime function name from CUPTI, here is code snippet of it:

```c++
  if (cbInfo->callbackSite == CUPTI_API_ENTER)
  {
      traceData->functionName = cbInfo->functionName; // get cuda function name 
      CUPTI_CALL(cuptiGetTimestamp(&startTimestamp));
      traceData->startTimestamp = startTimestamp;
      traceData->memcpy_bytes = ((cudaMemcpy_v3020_params *)(cbInfo->functionParams))->count;
      traceData->memcpy_kind = ((cudaMemcpy_v3020_params *)(cbInfo->functionParams))->kind;
  }
```
What makes me confused is that how does kineto get functions name of pytroch (e.g. `torch::autograd::AccumulateGrad`) ? Is the supported by CUPTI or you guys use other ways to implement ? 

2. What is the purpose of `KINETO_USE_DAEMON=1` ?
According to a [blog](https://pytorch.org/blog/automated-trace-collection/) I quote a pecie of it:
     > First, we modified PyTorch to register with the Dynolog daemon on start up. This feature is switched on by setting the environment variable KINETO_USE_DAEMON=True. With this environment variable set to True, the PyTorch Profiler periodically polls Dynolog to check for on-demand tracing requests.

     So does it mean that if the env variable was not set, then Pytorch profiler still enabled and it just doesn't send the trace info it captured  to user ? In other words, the env variable does not affect whether Pytorch Profiler is enabled. Am I right ? 

    I have also opened a similiar [issue](https://github.com/facebookincubator/dynolog/issues/195) in dynolog repo but I dont get any feedback yet.  I would appreciate if someone could answer these questions.

**Comment by shinytang6** [comment]
@stricklandye  The first issue, as far as I understand, is that pytorch profiler pushes events to kineto actively, not by CUPTI itself

**Comment by shinytang6** [comment]
> @shinytang6 Thanks for your reply. Could you please tell me where is the source code related to this? i.e. Pytroch Profiler pushes events to kineto. :D

maybe you can check this:
https://github.com/pytorch/pytorch/blob/e1f159e6b2c0b5d2d169569c490f182771ac643b/torch/csrc/profiler/collection.cpp#L805

**Comment by stricklandye** [comment]
I see. Hope someone else could answer the second questions. I will close this issue in few days.

**Comment by aaronenyeshi** [comment]
> 1. How does kineto get pytroch functions name?
Kineto uses CUPTI to get the CUDA Runtime and launch names as well the as CUDA kernel names. Kineto interacts with PyTorch Profiler (inside of pytorch/pytorch repo), which helps Kineto get the PyTorch runtime function names. We also have a feature called Python Tracing, enabled by `with_stack=True`, which turns on the python tracer, and collects all the python runtime stacks too.

> 2. What is the purpose of KINETO_USE_DAEMON=1 ?
This is a new OSS feature meant to enable on-demand profiling. When the dynolog daemon is enable via this env var, the daemon can directly request Kineto to perform a GPU trace collection. The env variable does not affect whether Kineto is on or not, since Kineto can be used via PyTorch Profiler API calls.
