### ISSUE TITLE
In Overview page, time unit error

### ISSUE THREAD

**Issue by Aiuan** [pytorch/kineto#851]
Time unit error
![1](https://github.com/pytorch/kineto/assets/47709353/0803d343-60a8-416d-af05-877f37e8878c)

**Comment by aaronenyeshi** [comment]
The time unit should be 10^-6, or microseconds, or us.

**Comment by Aiuan** [comment]
But the bar chart below shows that the average time is between 50,000 and 60,000 microseconds, and I think the Time Duration in the table should be in milliseconds (ms).

**Comment by aaronenyeshi** [comment]
I don't think this is an error, microseconds == us. The chart shows durations in range of 40,000 us  - 60,000 us, and the table also shows time duration (us) average step time of 55,193 us.
