### ISSUE TITLE
Why PyTorch TensorBoard Profiler (Deprecated)

### ISSUE THREAD

**Issue by GuWei007** [pytorch/kineto#857]
What is the reson to deptecate  PyTorch TensorBoard Profiler ?
https://github.com/pytorch/kineto#pytorch-tensorboard-profiler-deprecated

**Comment by briancoutinho** [comment]
Microsoft was supporting the tensorboard profiler but their team was not able to support it lately.

**Comment by aaronenyeshi** [comment]
Question was answered, community is free to land diffs for tb_plugin !

**Comment by mypey** [comment]
That's really unfortunate. HTA is nice but provides very different types of information, at lower level and only focused on GPU. 
I can't find any satisfactory alternative to the PyTorch TensorBoard Profiler right now.
