### ISSUE TITLE
Add ProfilerAction.PAUSE

### ISSUE THREAD

**Issue by tchaton** [pytorch/kineto#86]
A ProfilerAction.PAUSE could be used to skip some batches when switching from train_dataloader to validation_dataloader

**Comment by gdankel** [comment]
I believe this is addressed in PT 1.9 via the new schedule args:
https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html#using-profiler-to-analyze-long-running-jobs

@tchaton can we close this?
