### ISSUE TITLE
How to add customized metadata with on demand profiling ? 

### ISSUE THREAD

**Issue by staugust** [pytorch/kineto#885]
When profiling with `torch.profiler.profile` ,  generated json file has a section called `distributedInfo` shown as below
```json
{
  "distributedInfo": {"backend": "nccl", "rank": 0, "world_size": 2}
}
```
But there's no such section in generated file when on-demand profiling is triggered.  As a result, Holistic Trace Analysis cannot be used to analysis those files. 
Is this by design or there's something to do to make those file generated by `kineto` have `distributedInfo` as well? Hoping some one can help. Thanks.

**Comment by aaronenyeshi** [comment]
This is a bug, if you would like, please submit a fix for this issue. cc @briancoutinho

**Comment by staugust** [comment]
> This is a bug, if you would like, please submit a fix for this issue. cc @briancoutinho

Thanks for kindly response,  I will give it a try in few days.

**Comment by sraikund16** [comment]
@staugust do you still plan on working on this?

**Comment by staugust** [comment]
@sraikund16   I'm afraid I don't have enough time to  work on this in next one or two weeks.  It would be great if you have time to solve it, otherwise,  I would work on this later.

**Comment by sraikund16** [comment]
@staugust I am going to take up this task, thanks

**Comment by sraikund16** [comment]
reopening because needs follow up

**Comment by sraikund16** [comment]
Closing for now as this was added for NCCL traces in https://github.com/facebookresearch/HolisticTraceAnalysis/pull/157

If there is a need for gloo/mpi backends we can reopen and do a follow up
