### ISSUE TITLE
KeyError: <torch_tb_profiler.profiler.node.OperatorNode object at 0x7f4a45dc3e80>

### ISSUE THREAD

**Issue by hnt2601** [pytorch/kineto#913]
I want to profile for T5 model with huggingface and deepspeed configuration like this but i got a issue.
```
accelerator = Accelerator()
model, optimizer, dataloader = accelerator.prepare(model, optimizer, train_loader)
with profile(
        activities=[
            torch.profiler.ProfilerActivity.CPU,
            torch.profiler.ProfilerActivity.CUDA,
        ],
        schedule=tracing_schedule,
        on_trace_ready=trace_handler,
        profile_memory=False,
        record_shapes=True,
        with_stack=True,
        with_flops=False,
    ) as prof:
        for step, batch in enumerate(dataloader):
            source, target = batch
            source = source.to(f"cuda:{args.device}")
            target = target.input_ids.to(f"cuda:{args.device}")

            with torch.profiler.record_function("# Forward Pass #"):
                loss = model.forward(
                    source.input_ids, source.attention_mask, labels=target
                ).loss

            with torch.profiler.record_function("# Loss Pass #"):
                loss = loss / training_args.gradient_accumulation_steps
            with torch.profiler.record_function("# Backward Pass #"):
                accelerator.backward(loss)
            with torch.profiler.record_function("# Optimizer Pass #"):
                if step % training_args.gradient_accumulation_steps == 0:
                    optimizer.step()
                    optimizer.zero_grad()

        prof.step()
```
Error:

`Traceback (most recent call last):
  File "debug.py", line 15, in <module>
    profile = parse_json_trace(trace_log)
  File "debug.py", line 10, in parse_json_trace
    return RunProfileData.from_json(worker_name, 0, trace_json)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/data.py", line 111, in from_json
    profile.process()
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/data.py", line 172, in process
    self.tid2tree, self.pl_tid2tree = parser.parse(self.events, self.forward_backward_events)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/event_parser.py", line 424, in parse
    tid2tree = builder.build_tree(tid2list, tid2zero_rt_list, staled_device_nodes, fwd_bwd_map=fwd_bwd_map)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/op_tree.py", line 46, in build_tree
    fwd_bwd_root = self._get_backward_roots(fwd_bwd_map, ts2parent, agg_nodes)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/op_tree.py", line 256, in _get_backward_roots
    fwd_to_bwdroot[fwd] = backward_nodes.pop(parent)
KeyError: <torch_tb_profiler.profiler.node.OperatorNode object at 0x7f4a45dc3e80>`

That my profile file: https://drive.google.com/file/d/1P4LoVhUapRFwJXaTgZcTQLrLG-Uv2s_i/view?usp=sharing

**Comment by aaronenyeshi** [comment]
Hi @hnt2601, the Tensorboard Plugin is deprecated. We are accepting any community PRs and bug fixes, but no longer actively maintaining it. Please feel free to submit any fixes. Thanks!

Ref: https://github.com/pytorch/kineto/blob/main/README.md#pytorch-tensorboard-profiler-deprecated
