### ISSUE TITLE
IN Build CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060, not found

### ISSUE THREAD

**Issue by pdeJamesBritton** [pytorch/kineto#960]
To solve a different issue I was doing steps from https://github.com/pytorch/pytorch/issues/62588 and at the make step I got the  errors below.
‘CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060’ was not declared in this scope;

Thank You

In file included from /home/j/snap/kineto/libkineto/third_party/googletest/googletest/include/gtest/gtest.h:387,
                 from /home/j/snap/kineto/libkineto/test/CuptiCallbackApiTest.cpp:12:
/home/j/snap/kineto/libkineto/test/CuptiCallbackApiTest.cpp: In function ‘void simple_cudaLaunchKernelExC_cb(CUpti_CallbackDomain, CUpti_CallbackId, const CUpti_CallbackData*)’:
/home/j/snap/kineto/libkineto/test/CuptiCallbackApiTest.cpp:44:19: error: ‘CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060’ was not declared in this scope; did you mean ‘CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_v7000’?
   44 |   EXPECT_EQ(cbid, CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/j/snap/kineto/libkineto/test/CuptiCallbackApiTest.cpp: In member function ‘virtual void CuptiCallbackApiTest_SimpleTest_Test::TestBody()’:
/home/j/snap/kineto/libkineto/test/CuptiCallbackApiTest.cpp:108:7: error: ‘CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060’ was not declared in this scope; did you mean ‘CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_v7000’?
  108 |       CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_v7000
In file included from /home/j/snap/kineto/libkineto/third_party/googletest/googletest/include/gtest/gtest.h:62:
/home/j/snap/kineto/libkineto/test/CuptiCallbackApiTest.cpp: In member function ‘virtual void CuptiCallbackApiTest_AllCallbacks_Test::TestBody()’:
/home/j/snap/kineto/libkineto/test/CuptiCallbackApiTest.cpp:186:7: error: ‘CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060’ was not declared in this scope; did you mean ‘CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_v7000’?
  186 |       CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [test/CMakeFiles/CuptiCallbackApiTest.dir/build.make:76: test/CMakeFiles/CuptiCallbackApiTest.dir/CuptiCallbackApiTest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:374: test/CMakeFiles/CuptiCallbackApiTest.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by pdeJamesBritton** [comment]
Also, after the cmake .. command I got the following warning:

CMake Warning (dev) in test/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "CuptiProfilerApiTest".
This warning is for project developers.  Use -Wno-dev to suppress it.

thank you

**Comment by aaronenyeshi** [comment]
Please check your version of CUPTI, it may need to be upgrade to CUDA Toolkit 12.0+
